/**
 * Comprehensive Human Design Content Descriptions — Czech
 * Contains detailed descriptions for all HD elements:
 * - 5 Types, 12 Profiles, 7 Authorities, 9 Centers
 * - 64 Gates with I Ching hexagram names
 * - 36 Channels with descriptions
 */

// ─── Gate Descriptions with I Ching Hexagrams ─────────────────────────────────

export const GATE_DESCRIPTIONS: Record<number, {
  name: string;
  iChing: string;
  hexagram: string;
  center: string;
  circuit: string;
  theme: string;
  description: string;
  giftKeyword: string;
  shadowKeyword: string;
}> = {
  1: { name: "Sebevyjádření", iChing: "Tvůrčí", hexagram: "☰", center: "G", circuit: "Individuální", theme: "Tvůrčí sebevyjádření", description: "Brána Sebevyjádření nese energii jedinečného tvůrčího přínosu. Když je tato brána aktivní, máte hlubokou touhu vyjádřit svou individuální kreativitu. Je to energie umělce, inovátora a originálního myslitele, který musí sdílet svůj jedinečný pohled se světem.", giftKeyword: "Svěžest", shadowKeyword: "Entropie" },
  2: { name: "Směr Já", iChing: "Přijímající", hexagram: "☷", center: "G", circuit: "Kolektivní", theme: "Vyšší poznání a směr", description: "Brána Směru Já je o receptivitě a vedení vyšším poznáním. Lidé s touto branou mají vrozený smysl pro směr v životě, i když ho nedokáží logicky vysvětlit. Je to energie mystika, který důvěřuje rozvíjení života.", giftKeyword: "Orientace", shadowKeyword: "Dezorientace" },
  3: { name: "Uspořádání", iChing: "Obtíž na začátku", hexagram: "☵☳", center: "Sakrální", circuit: "Individuální", theme: "Inovace skrze uspořádání", description: "Brána Uspořádání nese energii mutace a inovace. Představuje obtíž a krásu nových začátků. Lidé s touto branou jsou zde, aby přinášeli nový řád z chaosu a vytvářeli inovativní řešení transformující stávající vzorce.", giftKeyword: "Inovace", shadowKeyword: "Chaos" },
  4: { name: "Formulace", iChing: "Mladická pošetilost", hexagram: "☶☵", center: "Ajna", circuit: "Kolektivní", theme: "Mentální formulace", description: "Brána Formulace je o mentálním procesu hledání odpovědí a vytváření logických formulí. Lidé s touto branou mají neustálý mentální tlak nacházet řešení a chápat vzorce. Jsou přirozenými řešiteli problémů.", giftKeyword: "Porozumění", shadowKeyword: "Nesnášenlivost" },
  5: { name: "Pevné vzorce", iChing: "Čekání", hexagram: "☵☰", center: "Sakrální", circuit: "Kolektivní", theme: "Univerzální rytmy a vzorce", description: "Brána Pevných vzorců je o přirozených rytmech a trpělivosti čekat na správné načasování. Lidé s touto branou jsou hluboce spojeni s univerzálními cykly. Daří se jim, když ctí své přirozené rytmy.", giftKeyword: "Trpělivost", shadowKeyword: "Netrpělivost" },
  6: { name: "Tření", iChing: "Konflikt", hexagram: "☰☵", center: "Solární plexus", circuit: "Kmenový", theme: "Emocionální intimita", description: "Brána Tření je o emocionální vlně řídící intimitu a spojení. Tato brána kontroluje přístup k emocionální a fyzické blízkosti. Lidé s touto branou prožívají hluboké emocionální vlny ovlivňující jejich schopnost blízkosti.", giftKeyword: "Diplomacie", shadowKeyword: "Konflikt" },
  7: { name: "Role Já", iChing: "Armáda", hexagram: "☷☵", center: "G", circuit: "Kolektivní", theme: "Vedení a směr", description: "Brána Role Já je o vedení příkladem. Lidé s touto branou mají přirozenou schopnost vést a ovlivňovat ostatní skrze své autentické sebevyjádření. Je to demokratické vedení inspirující vizí.", giftKeyword: "Ctnost", shadowKeyword: "Rozdělení" },
  8: { name: "Příspěvek", iChing: "Soudržnost", hexagram: "☵☷", center: "Hrdlo", circuit: "Individuální", theme: "Jedinečný příspěvek", description: "Brána Příspěvku je o vytváření jedinečného a individuálního přínosu světu. Lidé s touto branou cítí hlubokou potřebu přispět něčím smysluplným a originálním.", giftKeyword: "Styl", shadowKeyword: "Průměrnost" },
  9: { name: "Soustředění", iChing: "Zkrocení malého", hexagram: "☴☰", center: "Sakrální", circuit: "Kolektivní", theme: "Odhodlání a soustředění", description: "Brána Soustředění je o síle koncentrace a pozornosti k detailu. Lidé s touto branou mají schopnost intenzivně se soustředit na malé věci, které dělají velký rozdíl.", giftKeyword: "Odhodlání", shadowKeyword: "Setrvačnost" },
  10: { name: "Chování Já", iChing: "Kráčení", hexagram: "☰☱", center: "G", circuit: "Individuální", theme: "Sebeláska a chování", description: "Brána Chování Já je o sebelásce a autentickém chování. Lidé s touto branou jsou zde, aby se bezpodmínečně milovali a chovali se způsobem věrným své přirozenosti.", giftKeyword: "Přirozenost", shadowKeyword: "Sebeposedlost" },
  11: { name: "Nápady", iChing: "Mír", hexagram: "☷☰", center: "Ajna", circuit: "Kolektivní", theme: "Konceptualizace nápadů", description: "Brána Nápadů je o stimulaci nových myšlenek a konceptů. Lidé s touto branou jsou přirozenými generátory nápadů, kteří jsou neustále inspirováni novými možnostmi.", giftKeyword: "Idealismus", shadowKeyword: "Nejasnost" },
  12: { name: "Opatrnost", iChing: "Stagnace", hexagram: "☰☷", center: "Hrdlo", circuit: "Individuální", theme: "Opatrné vyjádření", description: "Brána Opatrnosti řídí načasování sociálního vyjádření. Lidé s touto branou vědí, kdy mluvit a kdy mlčet. Jejich vyjádření je hluboce emocionální a může být hluboce dojemné, když přijde správný čas.", giftKeyword: "Čistota", shadowKeyword: "Marnivost" },
  13: { name: "Posluchač", iChing: "Společenství", hexagram: "☰☲", center: "G", circuit: "Kolektivní", theme: "Naslouchání a sbírání zkušeností", description: "Brána Posluchače je o schopnosti hluboce naslouchat a sbírat příběhy a zkušenosti ostatních. Lidé s touto branou jsou přirozenými důvěrníky, kterým ostatní svěřují svá tajemství.", giftKeyword: "Rozlišování", shadowKeyword: "Nesoulad" },
  14: { name: "Mocné dovednosti", iChing: "Velké vlastnictví", hexagram: "☲☰", center: "Sakrální", circuit: "Individuální", theme: "Posílení skrze zdroje", description: "Brána Mocných dovedností je o schopnosti posilovat skrze materiální zdroje a dovednosti. Lidé s touto branou mají přirozený talent vytvářet hojnost a směřovat zdroje k smysluplným účelům.", giftKeyword: "Kompetence", shadowKeyword: "Kompromis" },
  15: { name: "Extrémy", iChing: "Pokora", hexagram: "☷☶", center: "G", circuit: "Kolektivní", theme: "Láska k lidstvu a extrémy", description: "Brána Extrémů je o lásce k lidstvu vyjádřené skrze extrémní rytmy a vzorce. Lidé s touto branou oscilují mezi extrémy ve svém chování a životním stylu.", giftKeyword: "Magnetismus", shadowKeyword: "Nuda" },
  16: { name: "Dovednosti", iChing: "Nadšení", hexagram: "☳☷", center: "Hrdlo", circuit: "Kolektivní", theme: "Mistrovství skrze praxi", description: "Brána Dovedností je o nadšení pro rozvíjení mistrovství skrze praxi a opakování. Lidé s touto branou jsou poháněni zdokonalovat své dovednosti a sdílet svou odbornost.", giftKeyword: "Všestrannost", shadowKeyword: "Lhostejnost" },
  17: { name: "Názory", iChing: "Následování", hexagram: "☱☳", center: "Ajna", circuit: "Kolektivní", theme: "Logické názory", description: "Brána Názorů je o formování a sdílení logických názorů. Lidé s touto branou mají přirozenou schopnost vidět vzorce a formovat názory o tom, jak by věci měly fungovat.", giftKeyword: "Dalekovidnost", shadowKeyword: "Dogmatismus" },
  18: { name: "Korekce", iChing: "Práce na zkažených", hexagram: "☶☴", center: "Slezina", circuit: "Kolektivní", theme: "Intuitivní korekce", description: "Brána Korekce je o intuitivní touze opravovat a zlepšovat vzorce. Lidé s touto branou mají přirozené oko pro to, co je třeba opravit nebo zlepšit.", giftKeyword: "Integrita", shadowKeyword: "Kritičnost" },
  19: { name: "Touha", iChing: "Přiblížení", hexagram: "☷☱", center: "Kořen", circuit: "Kmenový", theme: "Citlivost k potřebám", description: "Brána Touhy je o citlivosti k základním potřebám komunity. Lidé s touto branou jsou hluboce naladěni na to, co ostatní potřebují a chtějí.", giftKeyword: "Citlivost", shadowKeyword: "Závislost" },
  20: { name: "Přítomnost", iChing: "Rozjímání", hexagram: "☴☷", center: "Hrdlo", circuit: "Individuální", theme: "Vědomí přítomného okamžiku", description: "Brána Přítomnosti je o síle vědomí přítomného okamžiku. Lidé s touto branou mají přirozenou schopnost být plně přítomni a vyjadřovat, co se děje v daném okamžiku.", giftKeyword: "Sebejistota", shadowKeyword: "Povrchnost" },
  21: { name: "Lovec", iChing: "Prokousnutí", hexagram: "☲☳", center: "Srdce", circuit: "Kmenový", theme: "Kontrola a vůle", description: "Brána Lovce je o vůli kontrolovat zdroje a výsledky. Lidé s touto branou mají silnou vůli a odhodlání dosáhnout toho, co chtějí. Jsou přirozenými vůdci, kteří přebírají kontrolu nad materiálními zdroji.", giftKeyword: "Autorita", shadowKeyword: "Kontrola" },
  22: { name: "Otevřenost", iChing: "Elegance", hexagram: "☶☲", center: "Solární plexus", circuit: "Individuální", theme: "Emocionální otevřenost a elegance", description: "Brána Otevřenosti je o emocionální eleganci a schopnosti naslouchat s otevřeným srdcem. Lidé s touto branou nesou hlubokou emocionální citlivost, která může ve správný čas dotknout a transformovat ostatní.", giftKeyword: "Laskavost", shadowKeyword: "Bezectnost" },
  23: { name: "Asimilace", iChing: "Rozpad", hexagram: "☶☷", center: "Hrdlo", circuit: "Individuální", theme: "Vyjádření individuálního poznání", description: "Brána Asimilace je o schopnosti překládat individuální poznatky do jazyka, kterému ostatní rozumí. Lidé s touto branou jsou zde, aby sdíleli jedinečné perspektivy, které mohou zpočátku znít zvláštně, ale nesou hlubokou pravdu.", giftKeyword: "Jednoduchost", shadowKeyword: "Složitost" },
  24: { name: "Racionalizace", iChing: "Návrat", hexagram: "☷☳", center: "Ajna", circuit: "Individuální", theme: "Mentální přezkum a rekoncepce", description: "Brána Racionalizace je o mentálním procesu přezkoumávání a překonceptualizace myšlenek. Lidé s touto branou prožívají neustálou mentální smyčku přehodnocování a zdokonalování svého porozumění.", giftKeyword: "Vynalézavost", shadowKeyword: "Závislost" },
  25: { name: "Nevinnost", iChing: "Nevinnost", hexagram: "☰☳", center: "G", circuit: "Individuální", theme: "Univerzální láska a duch", description: "Brána Nevinnosti je o duchu univerzální lásky a přijetí. Lidé s touto branou nesou čistou, nevinnou energii, která je spojuje s božským. Jsou zde, aby milovali bezpodmínečně.", giftKeyword: "Přijetí", shadowKeyword: "Omezení" },
  26: { name: "Šibal", iChing: "Velká zkrocující síla", hexagram: "☶☰", center: "Srdce", circuit: "Kmenový", theme: "Ego a obchodní talent", description: "Brána Šibala je o síle přesvědčování a schopnosti prodávat myšlenky, produkty nebo vize. Lidé s touto branou mají přirozený talent pro marketing a přesvědčování ostatních o hodnotě toho, co nabízejí.", giftKeyword: "Umnost", shadowKeyword: "Pýcha" },
  27: { name: "Výživa", iChing: "Poskytování výživy", hexagram: "☶☳", center: "Sakrální", circuit: "Kmenový", theme: "Péče a výživa", description: "Brána Výživy je o pečující energii, která živí a udržuje ostatní. Lidé s touto branou mají hlubokou touhu pečovat o ty kolem sebe. Je to energie pečovatele a poskytovatele.", giftKeyword: "Nezištnost", shadowKeyword: "Sobeckost" },
  28: { name: "Hráč", iChing: "Přesila velkého", hexagram: "☱☴", center: "Slezina", circuit: "Individuální", theme: "Riskování a smysl", description: "Brána Hráče je o ochotě riskovat při hledání smyslu a účelu. Lidé s touto branou jsou poháněni najít, za co skutečně stojí bojovat. Jsou existenciálními válečníky hledajícími smysl.", giftKeyword: "Celistvost", shadowKeyword: "Bezúčelnost" },
  29: { name: "Vytrvalost", iChing: "Propast", hexagram: "☵☵", center: "Sakrální", circuit: "Kolektivní", theme: "Závazek a říkání ano", description: "Brána Vytrvalosti je o síle závazku a schopnosti říci ano zkušenostem. Lidé s touto branou mají hlubokou kapacitu pro vytrvalost a oddanost, jakmile se k něčemu zaváží.", giftKeyword: "Oddanost", shadowKeyword: "Polovičatost" },
  30: { name: "Pocity", iChing: "Přilnavý oheň", hexagram: "☲☲", center: "Solární plexus", circuit: "Kolektivní", theme: "Touha a emocionální hloubka", description: "Brána Pocitů je o ohni touhy a emocionální intenzitě. Lidé s touto branou prožívají hluboké pocity a touhy, které je pohánějí hledat nové zkušenosti. Jsou zde, aby plně prožívali život.", giftKeyword: "Lehkost", shadowKeyword: "Touha" },
  31: { name: "Vedení", iChing: "Vliv", hexagram: "☱☶", center: "Hrdlo", circuit: "Kolektivní", theme: "Demokratické vedení", description: "Brána Vedení je o schopnosti ovlivňovat ostatní skrze demokratické vedení. Lidé s touto branou mají přirozenou autoritu, kterou ostatní uznávají a následují.", giftKeyword: "Vedení", shadowKeyword: "Arogance" },
  32: { name: "Kontinuita", iChing: "Trvání", hexagram: "☳☴", center: "Slezina", circuit: "Kmenový", theme: "Instinkt pro to, co přetrvá", description: "Brána Kontinuity je o instinktivním rozpoznání toho, co má trvalou hodnotu. Lidé s touto branou dokáží vycítit, co přetrvá a co ne. Jsou přirozenými ochránci zdrojů a tradic.", giftKeyword: "Zachování", shadowKeyword: "Selhání" },
  33: { name: "Soukromí", iChing: "Ústup", hexagram: "☰☶", center: "Hrdlo", circuit: "Kolektivní", theme: "Ústup a reflexe", description: "Brána Soukromí je o potřebě ústupu a reflexe po zkušenostech. Lidé s touto branou jsou přirozenými vypravěči, kteří sdílejí moudrost získanou ze svých zkušeností.", giftKeyword: "Moudrost", shadowKeyword: "Anonymita" },
  34: { name: "Síla", iChing: "Velká síla", hexagram: "☳☰", center: "Sakrální", circuit: "Individuální", theme: "Čistá sakrální síla", description: "Brána Síly je o surové sakrální energii a síle jednat. Lidé s touto branou nesou obrovskou životní sílu hledající vyjádření skrze akci. Je to čistá, individuální síla, která musí být správně využita.", giftKeyword: "Síla", shadowKeyword: "Násilí" },
  35: { name: "Změna", iChing: "Pokrok", hexagram: "☲☷", center: "Hrdlo", circuit: "Kolektivní", theme: "Pokrok skrze zkušenost", description: "Brána Změny je o touze po nových zkušenostech a pokroku. Lidé s touto branou jsou poháněni prozkoumávat a prožívat vše, co život nabízí. Jsou dobrodruhy kolektivu.", giftKeyword: "Dobrodružství", shadowKeyword: "Hlad" },
  36: { name: "Krize", iChing: "Zatmění světla", hexagram: "☷☲", center: "Solární plexus", circuit: "Kolektivní", theme: "Emocionální krize a růst", description: "Brána Krize je o emocionální zkušenosti krize jako katalyzátoru růstu. Lidé s touto branou jsou přitahováni k intenzivním emocionálním zkušenostem, které nakonec vedou k moudrosti a soucitu.", giftKeyword: "Lidskost", shadowKeyword: "Turbulence" },
  37: { name: "Přátelství", iChing: "Rodina", hexagram: "☴☲", center: "Solární plexus", circuit: "Kmenový", theme: "Komunita a přátelství", description: "Brána Přátelství je o emocionálních poutech vytvářejících komunitu a rodinu. Lidé s touto branou jsou přirozenými budovateli komunity, kteří vytvářejí silné vazby skrze emocionální spojení.", giftKeyword: "Rovnost", shadowKeyword: "Slabost" },
  38: { name: "Bojovník", iChing: "Opozice", hexagram: "☲☱", center: "Kořen", circuit: "Individuální", theme: "Boj za smysl", description: "Brána Bojovníka je o tlaku bojovat za individuální smysl a účel. Lidé s touto branou jsou poháněni vnitřním ohněm najít a bránit to, na čem skutečně záleží. Jsou duchovními válečníky.", giftKeyword: "Vytrvalost", shadowKeyword: "Boj" },
  39: { name: "Provokace", iChing: "Překážka", hexagram: "☵☶", center: "Kořen", circuit: "Individuální", theme: "Probouzení ducha", description: "Brána Provokace je o tlaku vyvolávat emocionální reakce v ostatních, aby probudila jejich ducha. Lidé s touto branou mají přirozenou schopnost tlačit na citlivá místa ostatních způsobem, který nakonec slouží růstu.", giftKeyword: "Dynamika", shadowKeyword: "Provokace" },
  40: { name: "Samota", iChing: "Osvobození", hexagram: "☳☵", center: "Srdce", circuit: "Kmenový", theme: "Vůle a samota", description: "Brána Samoty je o potřebě samoty k obnovení vůle. Lidé s touto branou potřebují pravidelné období o samotě k dobití své ego energie. Komunitě nejlépe slouží, když ctí svou potřebu prostoru.", giftKeyword: "Odhodlání", shadowKeyword: "Vyčerpání" },
  41: { name: "Stažení", iChing: "Úbytek", hexagram: "☶☱", center: "Kořen", circuit: "Kolektivní", theme: "Představivost a touha", description: "Brána Stažení je o tlaku touhy a představivosti. Lidé s touto branou cítí neustálý tlak představovat si nové možnosti a zkušenosti. Je to výchozí bod veškeré lidské zkušenosti.", giftKeyword: "Anticipace", shadowKeyword: "Fantazie" },
  42: { name: "Růst", iChing: "Přírůstek", hexagram: "☴☳", center: "Sakrální", circuit: "Kolektivní", theme: "Růst a dokončení", description: "Brána Růstu je o energii dovést věci k dokončení a maximalizovat růst. Lidé s touto branou mají sakrální energii dotáhnout věci k jejich přirozenému závěru.", giftKeyword: "Odpoutanost", shadowKeyword: "Očekávání" },
  43: { name: "Vhled", iChing: "Průlom", hexagram: "☱☰", center: "Ajna", circuit: "Individuální", theme: "Mentální průlom", description: "Brána Vhledu je o náhlých mentálních průlomech a jedinečném poznání. Lidé s touto branou prožívají záblesky vhledu přicházející z hlubokého vnitřního vědění. Jejich vhledy jsou individuální a často předbíhají dobu.", giftKeyword: "Vhled", shadowKeyword: "Hluchota" },
  44: { name: "Bdělost", iChing: "Přicházení vstříc", hexagram: "☰☴", center: "Slezina", circuit: "Kmenový", theme: "Instinktivní bdělost", description: "Brána Bdělosti je o instinktivní schopnosti rozpoznávat vzorce a potenciál. Lidé s touto branou mají bystré smysly pro to, co bude fungovat v materiálním světě. Dokáží vycítit úspěch a příležitost.", giftKeyword: "Týmová práce", shadowKeyword: "Zasahování" },
  45: { name: "Shromažďovatel", iChing: "Shromáždění", hexagram: "☱☷", center: "Hrdlo", circuit: "Kmenový", theme: "Shromažďování zdrojů", description: "Brána Shromažďovatele je o schopnosti shromažďovat a distribuovat zdroje. Lidé s touto branou jsou přirozenými vůdci, kteří spojují lidi kolem sdílených materiálních cílů.", giftKeyword: "Synergie", shadowKeyword: "Dominance" },
  46: { name: "Odhodlání", iChing: "Tlačení vzhůru", hexagram: "☷☴", center: "G", circuit: "Kolektivní", theme: "Láska k tělu", description: "Brána Odhodlání je o lásce k fyzickému tělu a odhodlání uspět skrze ztělesnění. Lidé s touto branou jsou hluboce spojeni se svou fyzickou zkušeností a nacházejí úspěch tím, že jsou na správném místě ve správný čas.", giftKeyword: "Radost", shadowKeyword: "Vážnost" },
  47: { name: "Realizace", iChing: "Útlak", hexagram: "☱☵", center: "Ajna", circuit: "Kolektivní", theme: "Dávání smyslu abstraktnímu", description: "Brána Realizace je o mentálním procesu dávání smyslu abstraktním zkušenostem. Lidé s touto branou se neustále snaží pochopit a vyjádřit, co prožili. Je to moment 'aha'.", giftKeyword: "Transmutace", shadowKeyword: "Útlak" },
  48: { name: "Hloubka", iChing: "Studna", hexagram: "☵☴", center: "Slezina", circuit: "Kolektivní", theme: "Hloubka poznání", description: "Brána Hloubky je o hlubokém prameni poznání a strachu z nedostatečnosti. Lidé s touto branou mají přístup k hluboké úrovni porozumění, ale mohou se obávat, že toho nevědí dost.", giftKeyword: "Vynalézavost", shadowKeyword: "Nedostatečnost" },
  49: { name: "Revoluce", iChing: "Revoluce", hexagram: "☱☲", center: "Solární plexus", circuit: "Kmenový", theme: "Emocionální revoluce", description: "Brána Revoluce je o emocionální síle přijímat nebo odmítat, revolucionizovat nebo udržovat status quo. Lidé s touto branou mají emocionální citlivost vědět, kdy je v vztazích a komunitách potřebná změna.", giftKeyword: "Revoluce", shadowKeyword: "Reakce" },
  50: { name: "Hodnoty", iChing: "Kotel", hexagram: "☲☴", center: "Slezina", circuit: "Kmenový", theme: "Kmenové hodnoty a zákony", description: "Brána Hodnot je o stanovování a udržování hodnot a zákonů chránících komunitu. Lidé s touto branou jsou strážci kmenových hodnot a mají hluboký smysl pro odpovědnost vůči ostatním.", giftKeyword: "Rovnováha", shadowKeyword: "Korupce" },
  51: { name: "Šok", iChing: "Probouzení", hexagram: "☳☳", center: "Srdce", circuit: "Individuální", theme: "Soutěživý duch a šok", description: "Brána Šoku je o vůli soutěžit a schopnosti šokovat ostatní do probuzení. Lidé s touto branou jsou duchovními válečníky, kteří využívají moment překvapení k zasvěcení ostatních do nových úrovní vědomí.", giftKeyword: "Iniciativa", shadowKeyword: "Agitace" },
  52: { name: "Klid", iChing: "Zachování klidu", hexagram: "☶☶", center: "Kořen", circuit: "Kolektivní", theme: "Soustředění a klid", description: "Brána Klidu je o tlaku být v klidu a soustředit se. Lidé s touto branou mají schopnost sedět v klidu a hluboce se soustředit, vytvářejíce základ klidné koncentrace podporující detailní práci.", giftKeyword: "Zdrženlivost", shadowKeyword: "Stres" },
  53: { name: "Začátky", iChing: "Vývoj", hexagram: "☴☶", center: "Kořen", circuit: "Kolektivní", theme: "Zahajování nových cyklů", description: "Brána Začátků je o tlaku začínat nové věci a zahajovat nové cykly. Lidé s touto branou cítí neustálou touhu začínat nové projekty, zkušenosti a fáze života.", giftKeyword: "Expanze", shadowKeyword: "Nezralost" },
  54: { name: "Ambice", iChing: "Vdávající se dívka", hexagram: "☳☱", center: "Kořen", circuit: "Kmenový", theme: "Touha a ambice", description: "Brána Ambice je o tlaku povznést se v materiálním světě skrze ambici a touhu. Lidé s touto branou jsou přirozeně ambiciózní a poháněni zlepšovat svou pozici v kmenové hierarchii.", giftKeyword: "Aspirace", shadowKeyword: "Chamtivost" },
  55: { name: "Duch", iChing: "Hojnost", hexagram: "☳☲", center: "Solární plexus", circuit: "Individuální", theme: "Emocionální duch a hojnost", description: "Brána Ducha je o emocionální hloubce spojující se s duchovní hojností. Lidé s touto branou nesou hlubokou emocionální citlivost, která může přistupovat ke stavům hluboké duchovní bohatosti.", giftKeyword: "Svoboda", shadowKeyword: "Oběť" },
  56: { name: "Stimulace", iChing: "Poutník", hexagram: "☲☶", center: "Hrdlo", circuit: "Kolektivní", theme: "Vyprávění a stimulace", description: "Brána Stimulace je o schopnosti stimulovat ostatní skrze vyprávění a sdílení zkušeností. Lidé s touto branou jsou přirozenými vypravěči, kteří oživují myšlenky skrze živé příběhy.", giftKeyword: "Obohacení", shadowKeyword: "Rozptylování" },
  57: { name: "Intuice", iChing: "Jemnost", hexagram: "☴☴", center: "Slezina", circuit: "Individuální", theme: "Intuitivní jasnost", description: "Brána Intuice je o nejpronikavější formě vědomí — intuitivní jasnosti v přítomném okamžiku. Lidé s touto branou mají přístup k jemnému, ale mocnému intuitivnímu vědění operujícímu v přítomnosti.", giftKeyword: "Intuice", shadowKeyword: "Neklid" },
  58: { name: "Vitalita", iChing: "Radostnost", hexagram: "☱☱", center: "Kořen", circuit: "Kolektivní", theme: "Radost a vitalita", description: "Brána Vitality je o tlaku nacházet radost a vitalitu v životě. Lidé s touto branou jsou poháněni opravovat a zlepšovat věci, aby ve světě vytvářeli více radosti a živosti.", giftKeyword: "Vitalita", shadowKeyword: "Nespokojenost" },
  59: { name: "Sexualita", iChing: "Rozptýlení", hexagram: "☴☵", center: "Sakrální", circuit: "Kmenový", theme: "Intimita a plodnost", description: "Brána Sexuality je o sakrální energii intimity, plodnosti a bourání bariér mezi lidmi. Lidé s touto branou mají mocnou energii pro vytváření intimních vazeb a nového života.", giftKeyword: "Intimita", shadowKeyword: "Nepoctivost" },
  60: { name: "Omezení", iChing: "Omezení", hexagram: "☵☱", center: "Kořen", circuit: "Individuální", theme: "Přijetí omezení", description: "Brána Omezení je o tlaku přijímat a překonávat omezení. Lidé s touto branou chápou, že skutečná svoboda přichází skrze přijetí omezení a práci v rámci hranic k vytvoření něčeho nového.", giftKeyword: "Realismus", shadowKeyword: "Omezení" },
  61: { name: "Tajemství", iChing: "Vnitřní pravda", hexagram: "☴☱", center: "Hlava", circuit: "Individuální", theme: "Vnitřní pravda a tajemství", description: "Brána Tajemství je o tlaku poznat nepoznatelné a proniknout do tajemství existence. Lidé s touto branou jsou poháněni hlubokou potřebou pochopit základní pravdy života.", giftKeyword: "Inspirace", shadowKeyword: "Psychóza" },
  62: { name: "Detail", iChing: "Přesila malého", hexagram: "☳☶", center: "Hrdlo", circuit: "Kolektivní", theme: "Vyjadřování detailů", description: "Brána Detailu je o schopnosti přesně vyjadřovat a komunikovat detaily. Lidé s touto branou mají talent přesně pojmenovávat věci a jasně komunikovat faktické informace.", giftKeyword: "Přesnost", shadowKeyword: "Intelektualismus" },
  63: { name: "Pochybnost", iChing: "Po dokončení", hexagram: "☵☲", center: "Hlava", circuit: "Kolektivní", theme: "Logická pochybnost a dotazování", description: "Brána Pochybnosti je o mentálním tlaku zpochybňovat a pochybovat za účelem nalezení logických odpovědí. Lidé s touto branou jsou poháněni potřebou ověřovat a validovat skrze logické zkoumání.", giftKeyword: "Zkoumání", shadowKeyword: "Pochybnost" },
  64: { name: "Zmatek", iChing: "Před dokončením", hexagram: "☲☵", center: "Hlava", circuit: "Kolektivní", theme: "Mentální tlak dávat smysl", description: "Brána Zmatku je o mentálním tlaku dávat smysl minulým zkušenostem. Lidé s touto branou prožívají neustálý proud mentálních obrazů a vzpomínek hledajících rozuzlení a porozumění.", giftKeyword: "Představivost", shadowKeyword: "Zmatek" },
};

// ─── Channel Descriptions ─────────────────────────────────────────────────────

export const CHANNEL_DESCRIPTIONS: Record<string, {
  name: string;
  gates: [number, number];
  centers: [string, string];
  circuit: string;
  theme: string;
  description: string;
}> = {
  "64-47": { name: "Kanál abstrakce", gates: [64, 47], centers: ["Hlava", "Ajna"], circuit: "Kolektivní", theme: "Mentální aktivita smíšená s jasností", description: "Tento kanál vytváří neustálý mentální proces přezkoumávání minulých zkušeností a dávání jim smyslu. Lidé s tímto kanálem jsou abstraktní myslitelé, kteří zpracovávají život skrze mentální obrazy a nakonec dospívají k hlubokým realizacím." },
  "61-24": { name: "Kanál vědomí", gates: [61, 24], centers: ["Hlava", "Ajna"], circuit: "Individuální", theme: "Myslitel od inspirace ke konceptu", description: "Tento kanál spojuje tlak poznat nepoznatelné s mentálním procesem racionalizace. Lidé s tímto kanálem jsou hlubocí myslitelé, kteří přijímají inspirace a pak pracují na jejich konceptualizaci do porozumění." },
  "63-4": { name: "Kanál logiky", gates: [63, 4], centers: ["Hlava", "Ajna"], circuit: "Kolektivní", theme: "Mentální pohoda smíšená s pochybností", description: "Tento kanál vytváří logickou mysl, která zpochybňuje vše a hledá vzorce a formule. Lidé s tímto kanálem jsou přirození vědci a logici, kteří potřebují pochopit základní vzorce života." },
  "17-62": { name: "Kanál přijetí", gates: [17, 62], centers: ["Ajna", "Hrdlo"], circuit: "Kolektivní", theme: "Organizátor — od názoru k detailu", description: "Tento kanál spojuje logické názory s přesnou komunikací detailů. Lidé s tímto kanálem mají schopnost formulovat logické pohledy a sdílet je přesně a fakticky." },
  "11-56": { name: "Kanál zvědavosti", gates: [11, 56], centers: ["Ajna", "Hrdlo"], circuit: "Kolektivní", theme: "Hledač — od nápadů ke stimulaci", description: "Tento kanál spojuje generování nápadů se schopností stimulovat ostatní skrze vyprávění. Lidé s tímto kanálem jsou přirození vypravěči, kteří oživují abstraktní koncepty skrze živé příběhy." },
  "43-23": { name: "Kanál strukturování", gates: [43, 23], centers: ["Ajna", "Hrdlo"], circuit: "Individuální", theme: "Individualista — od vhledu k asimilaci", description: "Tento kanál spojuje individuální mentální průlomy se schopností je sdílet s ostatními. Lidé s tímto kanálem přijímají jedinečné vhledy a pak je překládají do jazyka, kterému ostatní mohou rozumět." },
  "47-64": { name: "Kanál abstrakce", gates: [47, 64], centers: ["Ajna", "Hlava"], circuit: "Kolektivní", theme: "Abstraktní mysl", description: "Viz kanál 64-47." },
  "4-63": { name: "Kanál logiky", gates: [4, 63], centers: ["Ajna", "Hlava"], circuit: "Kolektivní", theme: "Logická mysl", description: "Viz kanál 63-4." },
  "24-61": { name: "Kanál vědomí", gates: [24, 61], centers: ["Ajna", "Hlava"], circuit: "Individuální", theme: "Vědomá mysl", description: "Viz kanál 61-24." },
  "62-17": { name: "Kanál přijetí", gates: [62, 17], centers: ["Hrdlo", "Ajna"], circuit: "Kolektivní", theme: "Logický organizátor", description: "Viz kanál 17-62." },
  "56-11": { name: "Kanál zvědavosti", gates: [56, 11], centers: ["Hrdlo", "Ajna"], circuit: "Kolektivní", theme: "Hledač příběhů", description: "Viz kanál 11-56." },
  "23-43": { name: "Kanál strukturování", gates: [23, 43], centers: ["Hrdlo", "Ajna"], circuit: "Individuální", theme: "Individuální vhled", description: "Viz kanál 43-23." },
  "16-48": { name: "Kanál vlnové délky", gates: [16, 48], centers: ["Hrdlo", "Slezina"], circuit: "Kolektivní", theme: "Talent — od dovedností k hloubce", description: "Tento kanál spojuje nadšení pro rozvíjení dovedností s hlubokou studnicí poznání. Lidé s tímto kanálem jsou talentovaní jedinci, kteří rozvíjejí mistrovství skrze hlubokou praxi." },
  "20-57": { name: "Kanál přítomnosti", gates: [20, 57], centers: ["Hrdlo", "Slezina"], circuit: "Individuální", theme: "Pronikavost — od přítomnosti k intuici", description: "Tento kanál spojuje vědomí přítomného okamžiku s intuitivní jasností. Lidé s tímto kanálem mají schopnost být plně přítomni a jednat z místa intuitivního vědění." },
  "20-34": { name: "Kanál karizmy", gates: [20, 34], centers: ["Hrdlo", "Sakrální"], circuit: "Individuální", theme: "Zaneprázdněný — od přítomnosti k síle", description: "Tento kanál spojuje vědomí přítomného okamžiku s čistou sakrální silou. Lidé s tímto kanálem jsou přirozeně charismatičtí jedinci, kteří jednají s mocí a přítomností." },
  "31-7": { name: "Kanál alfa", gates: [31, 7], centers: ["Hrdlo", "G"], circuit: "Kolektivní", theme: "Vůdce — od vedení ke směru", description: "Tento kanál spojuje demokratické vedení s rolí Já. Lidé s tímto kanálem jsou přirození vůdci, kteří inspirují ostatní svou autenticitou a vizí." },
  "8-1": { name: "Kanál inspirace", gates: [8, 1], centers: ["Hrdlo", "G"], circuit: "Individuální", theme: "Kreativní vzor — od příspěvku k sebevyjádření", description: "Tento kanál spojuje potřebu přispívat s tvůrčím sebevyjádřením. Lidé s tímto kanálem jsou inspirativní jedinci, jejichž jedinečné vyjádření přitahuje ostatní." },
  "33-13": { name: "Kanál proroka", gates: [33, 13], centers: ["Hrdlo", "G"], circuit: "Kolektivní", theme: "Svědek — od soukromí k posluchači", description: "Tento kanál spojuje potřebu ústupu a reflexe se schopností naslouchat a sbírat zkušenosti. Lidé s tímto kanálem jsou přirození svědci lidské zkušenosti." },
  "45-21": { name: "Kanál peněz", gates: [45, 21], centers: ["Hrdlo", "Srdce"], circuit: "Kmenový", theme: "Materialista — od shromažďování k lovci", description: "Tento kanál spojuje shromažďování zdrojů s vůlí kontrolovat a řídit. Lidé s tímto kanálem jsou přirození obchodníci a manažeři materiálních zdrojů." },
  "12-22": { name: "Kanál otevřenosti", gates: [12, 22], centers: ["Hrdlo", "Solární plexus"], circuit: "Individuální", theme: "Socialita — od opatrnosti k otevřenosti", description: "Tento kanál spojuje opatrné vyjádření s emocionální otevřeností. Lidé s tímto kanálem jsou hluboce emocionální jedinci, jejichž vyjádření může být hluboce dojemné, když přijde správný čas." },
  "35-36": { name: "Kanál nestálosti", gates: [35, 36], centers: ["Hrdlo", "Solární plexus"], circuit: "Kolektivní", theme: "Hledač zkušeností — od změny ke krizi", description: "Tento kanál spojuje touhu po nových zkušenostech s emocionální hloubkou krize. Lidé s tímto kanálem jsou přitahováni k intenzivním zkušenostem, které vedou k moudrosti." },
  "2-14": { name: "Kanál pulsu", gates: [2, 14], centers: ["G", "Sakrální"], circuit: "Individuální", theme: "Správce — od směru k mocným dovednostem", description: "Tento kanál spojuje vyšší poznání a směr s mocnými dovednostmi a zdroji. Lidé s tímto kanálem jsou přirození správci zdrojů vedení vyšším poznáním." },
  "15-5": { name: "Kanál rytmu", gates: [15, 5], centers: ["G", "Sakrální"], circuit: "Kolektivní", theme: "Průtok — od extrémů k pevným vzorcům", description: "Tento kanál spojuje lásku k extrémům s přirozenými rytmy a vzorci. Lidé s tímto kanálem jsou hluboce spojeni s přirozenými cykly a potřebují ctít své jedinečné rytmy." },
  "46-29": { name: "Kanál objevování", gates: [46, 29], centers: ["G", "Sakrální"], circuit: "Kolektivní", theme: "Hledač — od odhodlání k vytrvalosti", description: "Tento kanál spojuje lásku k fyzickému tělu s mocí závazku. Lidé s tímto kanálem jsou odhodlaní jedinci, kteří nacházejí úspěch skrze plné nasazení do zkušeností." },
  "10-20": { name: "Kanál probuzení", gates: [10, 20], centers: ["G", "Hrdlo"], circuit: "Individuální", theme: "Průzkumník — od chování k přítomnosti", description: "Tento kanál spojuje sebelásku a autentické chování s vědomím přítomného okamžiku. Lidé s tímto kanálem jsou přirození průzkumníci, kteří žijí plně přítomni." },
  "10-34": { name: "Kanál průzkumu", gates: [10, 34], centers: ["G", "Sakrální"], circuit: "Individuální", theme: "Průzkumník — od chování k síle", description: "Tento kanál spojuje autentické chování s čistou sakrální silou. Lidé s tímto kanálem jsou mocní jedinci, kteří jednají z místa autenticity a síly." },
  "10-57": { name: "Kanál dokonalé formy", gates: [10, 57], centers: ["G", "Slezina"], circuit: "Individuální", theme: "Průzkumník — od chování k intuici", description: "Tento kanál spojuje autentické chování s intuitivní jasností. Lidé s tímto kanálem jsou přirození průzkumníci vedení intuitivním vnitřním věděním." },
  "25-51": { name: "Kanál zasvěcení", gates: [25, 51], centers: ["G", "Srdce"], circuit: "Individuální", theme: "Hledač — od nevinnosti k šoku", description: "Tento kanál spojuje univerzální lásku s soutěživým duchem a šokem. Lidé s tímto kanálem jsou duchovní válečníci, kteří zasvěcují ostatní skrze šok a nevinnost." },
  "26-44": { name: "Kanál přenosu", gates: [26, 44], centers: ["Srdce", "Slezina"], circuit: "Kmenový", theme: "Přenašeč — od šibala k bdělosti", description: "Tento kanál spojuje přesvědčovací schopnosti s instinktivní bdělostí. Lidé s tímto kanálem mají přirozený talent rozpoznávat příležitosti a přenášet je ostatním." },
  "40-37": { name: "Kanál komunity", gates: [40, 37], centers: ["Srdce", "Solární plexus"], circuit: "Kmenový", theme: "Vůdce komunity — od samoty k přátelství", description: "Tento kanál spojuje potřebu samoty s emocionálními pouty přátelství. Lidé s tímto kanálem jsou přirození budovatelé komunity, kteří potřebují rovnováhu mezi samotou a spojením." },
  "51-25": { name: "Kanál zasvěcení", gates: [51, 25], centers: ["Srdce", "G"], circuit: "Individuální", theme: "Hledač — od šoku k nevinnosti", description: "Viz kanál 25-51." },
  "21-45": { name: "Kanál peněz", gates: [21, 45], centers: ["Srdce", "Hrdlo"], circuit: "Kmenový", theme: "Materialista — od lovce ke shromažďovateli", description: "Viz kanál 45-21." },
  "54-32": { name: "Kanál transformace", gates: [54, 32], centers: ["Kořen", "Slezina"], circuit: "Kmenový", theme: "Materialista — od ambice ke kontinuitě", description: "Tento kanál spojuje ambici s instinktem pro to, co přetrvá. Lidé s tímto kanálem jsou přirození podnikatelé, kteří budují trvalé struktury skrze ambici a rozlišování." },
  "38-28": { name: "Kanál boje", gates: [38, 28], centers: ["Kořen", "Slezina"], circuit: "Individuální", theme: "Hledač — od bojovníka k hráči", description: "Tento kanál spojuje boj za smysl s ochotou riskovat. Lidé s tímto kanálem jsou existenciální válečníci, kteří hledají smysl skrze výzvy a rizika." },
  "39-55": { name: "Kanál emocí", gates: [39, 55], centers: ["Kořen", "Solární plexus"], circuit: "Individuální", theme: "Romantik — od provokace k duchu", description: "Tento kanál spojuje provokaci s emocionálním duchem. Lidé s tímto kanálem jsou hluboce emocionální jedinci, kteří probouzejí ducha ostatních skrze provokaci." },
  "52-9": { name: "Kanál soustředění", gates: [52, 9], centers: ["Kořen", "Sakrální"], circuit: "Kolektivní", theme: "Soustředění — od klidu k zaměření", description: "Tento kanál spojuje klid a soustředění s odhodláním a pozorností k detailu. Lidé s tímto kanálem mají schopnost hluboce se soustředit a přinášet věci k dokonalosti." },
  "53-42": { name: "Kanál zrání", gates: [53, 42], centers: ["Kořen", "Sakrální"], circuit: "Kolektivní", theme: "Cyklický — od začátků k růstu", description: "Tento kanál spojuje zahajování nových cyklů s energií dovést je k dokončení. Lidé s tímto kanálem jsou přirození průvodci cykly začátku a konce." },
  "60-3": { name: "Kanál mutace", gates: [60, 3], centers: ["Kořen", "Sakrální"], circuit: "Individuální", theme: "Pulz — od omezení k uspořádání", description: "Tento kanál spojuje přijetí omezení s inovací a mutací. Lidé s tímto kanálem jsou přirození inovátori, kteří přinášejí nový řád skrze přijetí hranic." },
  "41-30": { name: "Kanál uznání", gates: [41, 30], centers: ["Kořen", "Solární plexus"], circuit: "Kolektivní", theme: "Hledač — od stažení k pocitům", description: "Tento kanál spojuje touhu a představivost s emocionální intenzitou. Lidé s tímto kanálem jsou poháněni hledat nové zkušenosti a prožívat emocionální hloubku." },
  "19-49": { name: "Kanál syntézy", gates: [19, 49], centers: ["Kořen", "Solární plexus"], circuit: "Kmenový", theme: "Citlivost — od touhy k revoluci", description: "Tento kanál spojuje citlivost k potřebám s emocionální silou revoluce. Lidé s tímto kanálem jsou hluboce citliví na potřeby komunity a mají sílu iniciovat změnu." },
  "58-18": { name: "Kanál soudu", gates: [58, 18], centers: ["Kořen", "Slezina"], circuit: "Kolektivní", theme: "Hledač — od vitality ke korekci", description: "Tento kanál spojuje vitalitu a radost s intuitivní korekcí. Lidé s tímto kanálem jsou přirození kritici kvality, kteří hledají zlepšení ve jménu radosti a vitality." },
  "48-16": { name: "Kanál vlnové délky", gates: [48, 16], centers: ["Slezina", "Hrdlo"], circuit: "Kolektivní", theme: "Talent — od hloubky k dovednostem", description: "Viz kanál 16-48." },
  "57-20": { name: "Kanál přítomnosti", gates: [57, 20], centers: ["Slezina", "Hrdlo"], circuit: "Individuální", theme: "Pronikavost — od intuice k přítomnosti", description: "Viz kanál 20-57." },
  "57-34": { name: "Kanál síly", gates: [57, 34], centers: ["Slezina", "Sakrální"], circuit: "Individuální", theme: "Archetype — od intuice k síle", description: "Tento kanál spojuje intuitivní jasnost s čistou sakrální silou. Lidé s tímto kanálem jsou mocní jedinci vedení intuitivním vnitřním věděním." },
  "44-26": { name: "Kanál přenosu", gates: [44, 26], centers: ["Slezina", "Srdce"], circuit: "Kmenový", theme: "Přenašeč — od bdělosti k šibalovi", description: "Viz kanál 26-44." },
  "50-27": { name: "Kanál zachování", gates: [50, 27], centers: ["Slezina", "Sakrální"], circuit: "Kmenový", theme: "Správce — od hodnot k výživě", description: "Tento kanál spojuje kmenové hodnoty s pečující energií. Lidé s tímto kanálem jsou přirození správci a pečovatelé, kteří udržují hodnoty a živí komunitu." },
  "32-54": { name: "Kanál transformace", gates: [32, 54], centers: ["Slezina", "Kořen"], circuit: "Kmenový", theme: "Materialista — od kontinuity k ambici", description: "Viz kanál 54-32." },
  "28-38": { name: "Kanál boje", gates: [28, 38], centers: ["Slezina", "Kořen"], circuit: "Individuální", theme: "Hledač — od hráče k bojovníku", description: "Viz kanál 38-28." },
  "18-58": { name: "Kanál soudu", gates: [18, 58], centers: ["Slezina", "Kořen"], circuit: "Kolektivní", theme: "Hledač — od korekce k vitalitě", description: "Viz kanál 58-18." },
  "27-50": { name: "Kanál zachování", gates: [27, 50], centers: ["Sakrální", "Slezina"], circuit: "Kmenový", theme: "Správce — od výživy k hodnotám", description: "Viz kanál 50-27." },
  "34-57": { name: "Kanál síly", gates: [34, 57], centers: ["Sakrální", "Slezina"], circuit: "Individuální", theme: "Archetype — od síly k intuici", description: "Viz kanál 57-34." },
  "34-10": { name: "Kanál průzkumu", gates: [34, 10], centers: ["Sakrální", "G"], circuit: "Individuální", theme: "Průzkumník — od síly k chování", description: "Viz kanál 10-34." },
  "34-20": { name: "Kanál karizmy", gates: [34, 20], centers: ["Sakrální", "Hrdlo"], circuit: "Individuální", theme: "Zaneprázdněný — od síly k přítomnosti", description: "Viz kanál 20-34." },
  "29-46": { name: "Kanál objevování", gates: [29, 46], centers: ["Sakrální", "G"], circuit: "Kolektivní", theme: "Hledač — od vytrvalosti k odhodlání", description: "Viz kanál 46-29." },
  "5-15": { name: "Kanál rytmu", gates: [5, 15], centers: ["Sakrální", "G"], circuit: "Kolektivní", theme: "Průtok — od pevných vzorců k extrémům", description: "Viz kanál 15-5." },
  "14-2": { name: "Kanál pulsu", gates: [14, 2], centers: ["Sakrální", "G"], circuit: "Individuální", theme: "Správce — od mocných dovedností ke směru", description: "Viz kanál 2-14." },
  "9-52": { name: "Kanál soustředění", gates: [9, 52], centers: ["Sakrální", "Kořen"], circuit: "Kolektivní", theme: "Soustředění — od zaměření ke klidu", description: "Viz kanál 52-9." },
  "42-53": { name: "Kanál zrání", gates: [42, 53], centers: ["Sakrální", "Kořen"], circuit: "Kolektivní", theme: "Cyklický — od růstu k začátkům", description: "Viz kanál 53-42." },
  "3-60": { name: "Kanál mutace", gates: [3, 60], centers: ["Sakrální", "Kořen"], circuit: "Individuální", theme: "Pulz — od uspořádání k omezení", description: "Viz kanál 60-3." },
  "59-6": { name: "Kanál plodnosti", gates: [59, 6], centers: ["Sakrální", "Solární plexus"], circuit: "Kmenový", theme: "Hledač — od sexuality k tření", description: "Tento kanál spojuje energii intimity a plodnosti s emocionální vlnou intimity. Lidé s tímto kanálem mají mocnou energii pro vytváření hlubokých intimních vazeb." },
  "6-59": { name: "Kanál plodnosti", gates: [6, 59], centers: ["Solární plexus", "Sakrální"], circuit: "Kmenový", theme: "Hledač — od tření k sexualitě", description: "Viz kanál 59-6." },
  "36-35": { name: "Kanál nestálosti", gates: [36, 35], centers: ["Solární plexus", "Hrdlo"], circuit: "Kolektivní", theme: "Hledač zkušeností — od krize ke změně", description: "Viz kanál 35-36." },
  "22-12": { name: "Kanál otevřenosti", gates: [22, 12], centers: ["Solární plexus", "Hrdlo"], circuit: "Individuální", theme: "Socialita — od otevřenosti k opatrnosti", description: "Viz kanál 12-22." },
  "37-40": { name: "Kanál komunity", gates: [37, 40], centers: ["Solární plexus", "Srdce"], circuit: "Kmenový", theme: "Vůdce komunity — od přátelství k samotě", description: "Viz kanál 40-37." },
  "55-39": { name: "Kanál emocí", gates: [55, 39], centers: ["Solární plexus", "Kořen"], circuit: "Individuální", theme: "Romantik — od ducha k provokaci", description: "Viz kanál 39-55." },
  "49-19": { name: "Kanál syntézy", gates: [49, 19], centers: ["Solární plexus", "Kořen"], circuit: "Kmenový", theme: "Citlivost — od revoluce k touze", description: "Viz kanál 19-49." },
  "30-41": { name: "Kanál uznání", gates: [30, 41], centers: ["Solární plexus", "Kořen"], circuit: "Kolektivní", theme: "Hledač — od pocitů ke stažení", description: "Viz kanál 41-30." },
  "7-31": { name: "Kanál alfa", gates: [7, 31], centers: ["G", "Hrdlo"], circuit: "Kolektivní", theme: "Vůdce — od směru k vedení", description: "Viz kanál 31-7." },
  "1-8": { name: "Kanál inspirace", gates: [1, 8], centers: ["G", "Hrdlo"], circuit: "Individuální", theme: "Kreativní vzor — od sebevyjádření k příspěvku", description: "Viz kanál 8-1." },
  "13-33": { name: "Kanál proroka", gates: [13, 33], centers: ["G", "Hrdlo"], circuit: "Kolektivní", theme: "Svědek — od posluchače k soukromí", description: "Viz kanál 33-13." },
};

// ─── Type Descriptions ────────────────────────────────────────────────────────

export const TYPE_DESCRIPTIONS: Record<string, {
  name: string;
  percentage: string;
  strategy: string;
  signature: string;
  notSelf: string;
  aura: string;
  description: string;
  strengths: string[];
  challenges: string[];
}> = {
  Manifestor: { name: "Manifestor", percentage: "~8%", strategy: "Informovat", signature: "Mír", notSelf: "Hněv", aura: "Uzavřená a odpuzující", description: "Manifestoři jsou iniciátoři systému Human Design. Jsou jediným typem navrženým jednat nezávisle bez čekání. Jejich uzavřená a odpuzující aura jim dává schopnost prorazit odpor a uskutečnit věci. Když Manifestoři informují ty, kteří budou jejich akcemi ovlivněni, nacházejí mír místo hněvu.", strengths: ["Přirození iniciátoři", "Nezávislé jednání", "Mocný dopad", "Vizionářské vedení"], challenges: ["Pocit kontroly", "Pamatovat informovat", "Nacházet mír s odpočinkem", "Vyrovnávání se s odporem"] },
  Generator: { name: "Generátor", percentage: "~37%", strategy: "Reagovat", signature: "Spokojenost", notSelf: "Frustrace", aura: "Otevřená a obklopující", description: "Generátoři jsou životní silou planety. Mají definované Sakrální centrum, které jim dává udržitelnou energii pro práci, kterou milují. Jejich otevřená a obklopující aura přitahuje život k nim. Když Generátoři čekají na reakci na to, co jim život přináší, nacházejí hlubokou spokojenost. Když iniciují, prožívají frustraci.", strengths: ["Udržitelná energie", "Mistrovství skrze reakci", "Magnetická aura", "Hluboká spokojenost v práci"], challenges: ["Čekání na reakci", "Neinicializovat", "Vědět kdy přestat", "Trpělivost s procesem"] },
  "Manifesting Generator": { name: "Manifestující Generátor", percentage: "~33%", strategy: "Reagovat, pak informovat", signature: "Spokojenost", notSelf: "Frustrace a hněv", aura: "Otevřená a obklopující", description: "Manifestující Generátoři kombinují životní sílu Generátora s iniciační silou Manifestora. Jsou vícevášnivými bytostmi, které se pohybují rychle a efektivně. Jejich strategie je čekat na reakci, pak informovat před jednáním. Jsou navrženi přeskakovat kroky a nacházet zkratky.", strengths: ["Vícevášniví", "Rychlí a efektivní", "Mocná energie", "Přirození multitaskeři"], challenges: ["Zpomalit pro reakci", "Informovat před jednáním", "Dokončovat co začnou", "Nepřeskakovat důležité kroky"] },
  Projector: { name: "Projektor", percentage: "~20%", strategy: "Čekat na pozvání", signature: "Úspěch", notSelf: "Hořkost", aura: "Soustředěná a absorbující", description: "Projektoři jsou průvodci a poradci systému Human Design. Jejich soustředěná a absorbující aura jim umožňuje hluboce vidět do ostatních. Jsou navrženi čekat na uznání a pozvání před sdílením své moudrosti. Když jsou uznáni a pozváni, Projektoři prožívají hluboký úspěch.", strengths: ["Hluboký vhled do ostatních", "Přirození průvodci", "Efektivní využití energie", "Moudrost a mistrovství"], challenges: ["Čekání na pozvání", "Správa energie", "Nedávat nevyžádané rady", "Vyrovnávání se s hořkostí"] },
  Reflector: { name: "Reflektor", percentage: "~1%", strategy: "Čekat lunární cyklus", signature: "Překvapení", notSelf: "Zklamání", aura: "Odolná a vzorkující", description: "Reflektoři jsou nejvzácnějším typem bez definovaných center. Jsou zrcadly komunity, odrážejícími zdraví a pohodu svého prostředí. Jejich strategie je čekat celý lunární cyklus (28 dní) před přijímáním důležitých rozhodnutí. Když ctí tento proces, prožívají překvapení života.", strengths: ["Barometr komunity", "Jedinečná perspektiva", "Moudrost měsíce", "Otevřenost ke všem zkušenostem"], challenges: ["Nalezení správného prostředí", "28denní rozhodovací proces", "Neidentifikovat se s ostatními", "Vyrovnávání se s nekonzistencí"] },
};

// ─── Authority Descriptions ───────────────────────────────────────────────────

export const AUTHORITY_DESCRIPTIONS: Record<string, {
  name: string;
  description: string;
  howToUse: string;
}> = {
  "Emotional (Solar Plexus)": { name: "Emocionální autorita", description: "Máte definované centrum Solárního plexu, což znamená, že prožíváte emocionální vlnu. Vaše pravda nikdy není v daném okamžiku — odhaluje se v průběhu času, jak jedete svou emocionální vlnou od výšky k hloubce a zpět.", howToUse: "Nikdy nepřijímejte důležitá rozhodnutí v horku okamžiku, ať se cítíte vysoko nebo nízko. Čekejte na emocionální jasnost — pocit klidného vědění, který přichází poté, co jste prožili celou škálu své emocionální vlny. Přespěte důležitá rozhodnutí. Mantra je: 'V přítomném okamžiku není pravda.'" },
  "Sacral": { name: "Sakrální autorita", description: "Vaše Sakrální centrum je vaší rozhodovací autoritou. Komunikuje skrze střevní reakce — zvuky jako 'uh-huh' (ano) nebo 'uhn-uhn' (ne) a fyzické pocity expanze nebo kontrakce.", howToUse: "Věnujte pozornost své střevní reakci, když vám život přináší příležitosti. Pokládejte si otázky ano/ne a sledujte reakci svého těla. Vaše Sakrální centrum mluví v okamžiku skrze zvuky a fyzické pocity. Důvěřujte počáteční střevní reakci — ví to dříve než vaše mysl." },
  "Splenic": { name: "Slezinová autorita", description: "Vaše centrum Sleziny je vaší rozhodovací autoritou. Komunikuje skrze spontánní intuitivní záblesky — tiché vnitřní vědění o tom, co je pro vás v daném okamžiku zdravé a bezpečné.", howToUse: "Důvěřujte svému prvnímu instinktu. Slezina mluví pouze jednou, tiše a v okamžiku. Je to jemné vědomí, že něco je pro vás správné nebo špatné. Nepřemýšlejte příliš — vaše slezinové vědomí je rychlejší než vaše mysl. Věnujte pozornost spontánním pocitům přitažlivosti nebo odporu." },
  "Ego Manifested": { name: "Ego manifestovaná autorita", description: "Vaše centrum Srdce/Ega je spojeno s Hrdlem, což vám dává autoritu přijímat rozhodnutí na základě toho, co vaše srdce skutečně chce a k čemu se může zavázat.", howToUse: "Naslouchejte tomu, co skutečně chcete a k čemu jste ochotni zavázat svou vůli. Ptejte se sami sebe: 'Je to to, co skutečně chci? Jsem ochoten do toho vložit srdce?' Vaše rozhodnutí by měla vycházet z upřímné touhy a vůle, ne z povinnosti." },
  "Ego Projected": { name: "Ego projektovaná autorita", description: "Vaše centrum Srdce/Ega je vaší autoritou, ale projektuje se skrze centrum G spíše než skrze Hrdlo. Potřebujete slyšet sami sebe mluvit o tom, co chcete, abyste nalezli jasnost.", howToUse: "Mluvte s důvěryhodnými přáteli o svých rozhodnutích a naslouchejte tomu, co z vás vychází. Uslyšíte svou pravdu ve svých vlastních slovech. Věnujte pozornost tomu, co vzrušuje vaše srdce a k čemu se skutečně cítíte ochotni zavázat." },
  "Self-Projected": { name: "Autorita projektovaného Já", description: "Vaše centrum G (Já) je vaší rozhodovací autoritou. Nacházíte jasnost tím, že slyšíte sami sebe mluvit o své identitě a směru.", howToUse: "Mluvte s důvěryhodnými lidmi o svých rozhodnutích a naslouchejte tomu, co říkáte. Vaše pravda se vynořuje skrze váš vlastní hlas. Věnujte pozornost výrokům o identitě ('Jsem...') a směru ('Chystám se...'). Vaše rozhodnutí by měla být v souladu s vaším smyslem pro sebe." },
  "Mental (Outer Authority)": { name: "Mentální/environmentální autorita", description: "Nemáte žádnou vnitřní autoritu pod Hrdlem. Váš rozhodovací proces zahrnuje mluvení o věcech s ostatními a pobývání ve správném prostředí.", howToUse: "Diskutujte svá rozhodnutí s různými lidmi a v různých prostředích. Všimněte si, jak různá místa a lidé ovlivňují vaši jasnost. Jste navrženi být ozvučnou deskou pro ostatní a na oplátku nacházíte svou vlastní jasnost skrze dialog a prostředí." },
  "Lunar (No Inner Authority)": { name: "Lunární autorita", description: "Jako Reflektor bez definovaných center je vaše autorita spojena s 28denním cyklem Měsíce. Potřebujete celý lunární cyklus k získání jasnosti v důležitých rozhodnutích.", howToUse: "Pro důležitá rozhodnutí čekejte celý 28denní lunární cyklus. Během této doby diskutujte rozhodnutí s různými lidmi a sledujte, jak se vaše perspektiva den za dnem mění. Veďte si měsíční deník. Po celém cyklu budete mít jasný pocit, co je pro vás správné." },
};

// ─── Profile Descriptions ─────────────────────────────────────────────────────

export const PROFILE_DESCRIPTIONS: Record<string, {
  name: string;
  theme: string;
  description: string;
  conscious: string;
  unconscious: string;
}> = {
  "1/3": { name: "Badatel / Mučedník", theme: "Základ skrze pokusy a omyly", description: "Profil 1/3 kombinuje potřebu pevného základu znalostí s učením skrze přímou zkušenost. Jste zde, abyste hluboce zkoumali a pak testovali, co jste se naučili, skrze pokusy a omyly. Váš život je cestou objevování skrze studium i zkušenost.", conscious: "Linka 1 (Badatel): Potřebujete se cítit bezpečně skrze hluboké znalosti a porozumění. Důkladně zkoumáte, než se zavážete.", unconscious: "Linka 3 (Mučedník): Učíte se skrze pokusy a omyly, objevujete co funguje a co ne skrze přímou zkušenost." },
  "1/4": { name: "Badatel / Oportunista", theme: "Základ skrze síť kontaktů", description: "Profil 1/4 kombinuje hluboké zkoumání se silou osobních sítí. Budujete pevný základ znalostí a pak ho sdílíte skrze své blízké vztahy. Příležitosti přicházejí skrze lidi, které znáte.", conscious: "Linka 1 (Badatel): Potřebujete důkladné porozumění a pevný základ před pohybem vpřed.", unconscious: "Linka 4 (Oportunista): Vaše příležitosti a vliv přicházejí skrze vaši osobní síť a blízké vztahy." },
  "2/4": { name: "Poustevník / Oportunista", theme: "Přirozený talent sdílený skrze sítě", description: "Profil 2/4 kombinuje přirozený talent se silou vztahů. Máte vrozené dary, které ostatní vidí, i když vy ne. Vaše talenty jsou vyvolávány a sdíleny skrze vaši osobní síť.", conscious: "Linka 2 (Poustevník): Máte přirozené talenty a potřebujete čas o samotě k jejich rozvoji. Možná nevidíte své vlastní dary.", unconscious: "Linka 4 (Oportunista): Vaše příležitosti přicházejí skrze vaši síť. Ostatní rozpoznávají a vyvolávají vaše talenty." },
  "2/5": { name: "Poustevník / Kacíř", theme: "Přirozený talent s univerzálním dopadem", description: "Profil 2/5 kombinuje přirozený talent se schopností nabízet praktická řešení ostatním. Máte vrozené dary a ostatní na vás projektují jako na někoho, kdo dokáže řešit problémy. Vaší výzvou je zvládání očekávání.", conscious: "Linka 2 (Poustevník): Máte přirozené talenty a potřebujete samotu k jejich rozvoji.", unconscious: "Linka 5 (Kacíř): Ostatní na vás projektují svá očekávání. Máte potenciál nabízet univerzální řešení." },
  "3/5": { name: "Mučedník / Kacíř", theme: "Pokusy a omyly s univerzálním dopadem", description: "Profil 3/5 kombinuje zkušenostní učení se schopností nabízet praktická řešení. Učíte se skrze pokusy a omyly a pak sdílíte svou těžce nabytou moudrost jako univerzální řešení.", conscious: "Linka 3 (Mučedník): Učíte se skrze přímou zkušenost, objevujete co funguje skrze pokusy a omyly.", unconscious: "Linka 5 (Kacíř): Ostatní na vás projektují očekávání. Vaše zkušenosti se stávají univerzálními lekcemi." },
  "3/6": { name: "Mučedník / Vzorový model", theme: "Pokusy a omyly stávající se moudrostí", description: "Profil 3/6 kombinuje zkušenostní učení s potenciálem pro moudrost a vzorové modelování. Váš život má tři fáze: experimentování (0-30), stažení a pozorování (30-50) a stávání se vzorovým modelem (50+).", conscious: "Linka 3 (Mučedník): Učíte se skrze pokusy a omyly, zejména v první fázi života.", unconscious: "Linka 6 (Vzorový model): Jste zde, abyste se nakonec stali živým příkladem moudrosti získané skrze zkušenost." },
  "4/6": { name: "Oportunista / Vzorový model", theme: "Vliv skrze sítě stávající se moudrostí", description: "Profil 4/6 kombinuje sílu osobních sítí s cestou k moudrosti vzorového modelu. Váš vliv přichází skrze vztahy a v průběhu času se rozvíjíte do moudrého průvodce.", conscious: "Linka 4 (Oportunista): Vaše příležitosti a vliv přicházejí skrze vaši osobní síť.", unconscious: "Linka 6 (Vzorový model): Procházíte třemi životními fázemi a nakonec se stáváte vzorovým modelem moudrosti." },
  "4/1": { name: "Oportunista / Badatel", theme: "Pevný osud skrze sítě a znalosti", description: "Profil 4/1 je jediným profilem 'pevného osudu'. Kombinujete sílu osobních sítí s hlubokým základem znalostí. Vaše cesta je relativně pevná a váš vliv přichází skrze sdílení vašich hlubokých znalostí ve vaší síti.", conscious: "Linka 4 (Oportunista): Vaše příležitosti přicházejí skrze vaši osobní síť a vztahy.", unconscious: "Linka 1 (Badatel): Máte hlubokou, nevědomou potřebu pevného základu znalostí." },
  "5/1": { name: "Kacíř / Badatel", theme: "Univerzální řešení skrze hluboké znalosti", description: "Profil 5/1 kombinuje schopnost nabízet univerzální řešení s hlubokým základem zkoumání. Ostatní na vás projektují svá očekávání a váš důkladný znalostní základ vám umožňuje dodávat praktická řešení.", conscious: "Linka 5 (Kacíř): Ostatní na vás projektují očekávání. Máte potenciál nabízet univerzální řešení.", unconscious: "Linka 1 (Badatel): Máte hlubokou, nevědomou potřebu zkoumat a budovat pevný znalostní základ." },
  "5/2": { name: "Kacíř / Poustevník", theme: "Univerzální řešení skrze přirozený talent", description: "Profil 5/2 kombinuje schopnost nabízet praktická řešení s přirozeným, vrozeným talentem. Ostatní vás vidí jako řešitele problémů a vaše přirozené dary tuto roli podporují.", conscious: "Linka 5 (Kacíř): Ostatní na vás projektují svá očekávání jako na řešitele problémů.", unconscious: "Linka 2 (Poustevník): Máte přirozené talenty, které podporují vaši schopnost nabízet řešení." },
  "6/2": { name: "Vzorový model / Poustevník", theme: "Moudrost skrze přirozený talent", description: "Profil 6/2 kombinuje cestu k moudrosti vzorového modelu s přirozeným talentem. Procházíte třemi životními fázemi a rozvíjíte své vrozené dary do moudrosti, která inspiruje ostatní.", conscious: "Linka 6 (Vzorový model): Prožíváte tři životní fáze a nakonec se stáváte moudrým vzorovým modelem.", unconscious: "Linka 2 (Poustevník): Máte přirozené talenty, které ostatní vidí, i když vy ne." },
  "6/3": { name: "Vzorový model / Mučedník", theme: "Moudrost skrze zkušenost", description: "Profil 6/3 kombinuje cestu k moudrosti se zkušenostním učením. Vaše cesta zahrnuje hluboké experimentování, zejména v první fázi života, a nakonec vede k hluboké moudrosti.", conscious: "Linka 6 (Vzorový model): Prožíváte tři životní fáze na cestě ke stávání se vzorovým modelem.", unconscious: "Linka 3 (Mučedník): Učíte se skrze pokusy a omyly a získáváte moudrost skrze přímou zkušenost." },
};

// ─── Center Descriptions ──────────────────────────────────────────────────────

export const CENTER_DESCRIPTIONS: Record<string, {
  name: string;
  biologicalCorrelation: string;
  theme: string;
  definedMeaning: string;
  openMeaning: string;
  notSelfQuestion: string;
}> = {
  Head: {
    name: "Hlava",
    biologicalCorrelation: "Epifýza / Mozek",
    theme: "Inspirace a mentální tlak",
    definedMeaning: "Máte konzistentní zdroj mentálního tlaku a inspirace. Ostatní mohou cítit váš mentální tlak. Jste navrženi inspirovat ostatní skrze své otázky a myšlenky.",
    openMeaning: "Přijímáte a zesilujete mentální tlak od ostatních. Můžete se cítit přetíženi otázkami a pochybnostmi, které nejsou vaše. Moudrost přichází z rozlišování, které otázky stojí za zodpovězení.",
    notSelfQuestion: "Snažím se zodpovědět otázky, které nejsou pro mě důležité nebo které mě nezajímají?"
  },
  Ajna: {
    name: "Ajna",
    biologicalCorrelation: "Přední a zadní mozek / Hypofýza",
    theme: "Mentální jistota a konceptualizace",
    definedMeaning: "Máte konzistentní způsob myšlení a zpracovávání informací. Vaše mysl funguje spolehlivým, předvídatelným způsobem. Ostatní mohou vnímat vaši mentální jistotu.",
    openMeaning: "Váš způsob myšlení je flexibilní a přizpůsobivý. Absorbujete různé způsoby myšlení od ostatních. Výzvou je nepřipoutat se k jednomu způsobu myšlení jako k absolutní pravdě.",
    notSelfQuestion: "Snažím se být si jistý/á věcmi, o kterých si jistý/á nejsem?"
  },
  Throat: {
    name: "Hrdlo",
    biologicalCorrelation: "Štítná žláza / Příštítná tělíska",
    theme: "Komunikace a manifestace",
    definedMeaning: "Máte konzistentní způsob komunikace a vyjadřování. Vaše slova a činy mají přirozenou autoritu. Jste navrženi mluvit a jednat ze svého vlastního impulsu.",
    openMeaning: "Vaše komunikace je ovlivněna prostředím a lidmi kolem vás. Můžete cítit tlak mluvit nebo jednat, abyste přitáhli pozornost. Moudrost přichází z mluvení, jen když máte co říci.",
    notSelfQuestion: "Snažím se přitáhnout pozornost tím, že mluvím nebo jednám?"
  },
  G: {
    name: "G Centrum (Já)",
    biologicalCorrelation: "Játra / Krev",
    theme: "Identita, láska a směr",
    definedMeaning: "Máte konzistentní smysl pro identitu a směr v životě. Víte, kdo jste a kam směřujete. Vaše přítomnost vyzařuje stabilní pocit Já.",
    openMeaning: "Vaše identita a směr jsou flexibilní a ovlivněné prostředím. Jste zde, abyste zrcadlili identitu a lásku ostatních. Moudrost přichází z pobytu na správných místech s správnými lidmi.",
    notSelfQuestion: "Hledám stále svou identitu nebo směr v životě?"
  },
  Heart: {
    name: "Srdce (Ego)",
    biologicalCorrelation: "Srdce / Žaludek / Žlučník",
    theme: "Vůle, ego a materiální svět",
    definedMeaning: "Máte konzistentní přístup k vůli a egové energii. Dokážete se zavazovat a dodržovat sliby. Jste navrženi pracovat a odpočívat v cyklech.",
    openMeaning: "Vaše vůle není konzistentní — přichází a odchází. Výzvou je nepřeceňovat se nebo nedávat sliby, které nemůžete dodržet. Moudrost přichází z přijetí, že nemusíte nic dokazovat.",
    notSelfQuestion: "Snažím se neustále dokazovat svou hodnotu nebo plnit sliby, které jsem neměl/a dávat?"
  },
  Sacral: {
    name: "Sakrální centrum",
    biologicalCorrelation: "Vaječníky / Varlata",
    theme: "Životní síla, sexualita a práce",
    definedMeaning: "Máte konzistentní přístup k životní síle a energii. Jste navrženi pracovat a vytvářet. Vaše sakrální reakce (uh-huh/uhn-uhn) je vaším průvodcem.",
    openMeaning: "Nemáte konzistentní přístup k sakrální energii. Absorbujete a zesilujete sakrální energii ostatních. Výzvou je vědět, kdy přestat a odpočinout si.",
    notSelfQuestion: "Vím, kdy mám dost? Odpočívám, když potřebuji?"
  },
  "Solar Plexus": {
    name: "Solární plexus",
    biologicalCorrelation: "Nervový systém / Plíce / Ledviny",
    theme: "Emoce, citlivost a duch",
    definedMeaning: "Máte emocionální vlnu, která ovlivňuje vaše rozhodování. Vaše pravda se odhaluje v průběhu času, ne v daném okamžiku. Jste navrženi čekat na emocionální jasnost.",
    openMeaning: "Absorbujete emoce ostatních a zesilujete je. Výzvou je rozlišovat, které emoce jsou vaše a které patří ostatním. Moudrost přichází z udržování emocionální neutrality.",
    notSelfQuestion: "Vyhýbám se konfrontaci nebo pravdě, abych udržel/a emocionální klid?"
  },
  Spleen: {
    name: "Slezina",
    biologicalCorrelation: "Lymfatický systém / Imunitní systém",
    theme: "Intuice, zdraví a přežití",
    definedMeaning: "Máte konzistentní přístup k intuitivnímu vědomí a zdraví. Vaše instinkty jsou spolehlivé. Jste navrženi důvěřovat svému prvnímu instinktu.",
    openMeaning: "Vaše intuice je variabilní a ovlivněná ostatními. Výzvou je nepřipoutat se k věcem, lidem nebo situacím, které nejsou pro vás zdravé. Moudrost přichází z naslouchání jemným intuitivním signálům.",
    notSelfQuestion: "Držím se věcí, situací nebo lidí, kteří nejsou pro mě dobří, protože se bojím?"
  },
  Root: {
    name: "Kořen",
    biologicalCorrelation: "Nadledvinky",
    theme: "Tlak, stres a pohon",
    definedMeaning: "Máte konzistentní přístup k adrenalinovému tlaku a pohonu. Jste navrženi pracovat pod tlakem a nacházet v něm rytmus. Váš tlak je stabilní a předvídatelný.",
    openMeaning: "Absorbujete a zesilujete adrenalínový tlak ostatních. Výzvou je nepospíchat věci jen proto, abyste se zbavili tlaku. Moudrost přichází z rozlišování, který tlak je váš.",
    notSelfQuestion: "Jednám spěšně nebo pod tlakem, jen abych se zbavil/a pocitu naléhavosti?"
  },
};
