/**
 * Comprehensive Human Design Content Descriptions
 * Contains detailed descriptions for all HD elements:
 * - 5 Types, 12 Profiles, 7 Authorities, 9 Centers
 * - 64 Gates with I Ching hexagram names
 * - 36 Channels with descriptions
 */

// ─── Gate Descriptions with I Ching Hexagrams ─────────────────────────────────

export const GATE_DESCRIPTIONS: Record<number, {
  name: string;
  iChing: string;
  hexagram: string;
  center: string;
  circuit: string;
  theme: string;
  description: string;
  giftKeyword: string;
  shadowKeyword: string;
}> = {
  1: { name: "Self-Expression", iChing: "The Creative", hexagram: "☰", center: "G", circuit: "Individual", theme: "Creative self-expression", description: "The Gate of Self-Expression carries the energy of unique creative contribution. When this gate is active, you have a deep drive to express your individual creativity. This is the energy of the artist, the innovator, and the original thinker who must share their unique perspective with the world.", giftKeyword: "Freshness", shadowKeyword: "Entropy" },
  2: { name: "The Direction of the Self", iChing: "The Receptive", hexagram: "☷", center: "G", circuit: "Collective", theme: "Higher knowing and direction", description: "The Gate of the Direction of the Self is about receptivity and being guided by a higher knowing. People with this gate have an innate sense of direction in life, even when they cannot explain it logically. This is the energy of the mystic who trusts the unfolding of life.", giftKeyword: "Orientation", shadowKeyword: "Dislocation" },
  3: { name: "Ordering", iChing: "Difficulty at the Beginning", hexagram: "☵☳", center: "Sacral", circuit: "Individual", theme: "Innovation through ordering", description: "The Gate of Ordering carries the energy of mutation and innovation. It represents the difficulty and beauty of new beginnings. People with this gate are here to bring new order out of chaos, creating innovative solutions that transform existing patterns.", giftKeyword: "Innovation", shadowKeyword: "Chaos" },
  4: { name: "Formulization", iChing: "Youthful Folly", hexagram: "☶☵", center: "Ajna", circuit: "Collective", theme: "Mental formulization", description: "The Gate of Formulization is about the mental process of finding answers and creating logical formulas. People with this gate have a constant mental pressure to find solutions and understand patterns. They are natural problem-solvers who seek to create order through logic.", giftKeyword: "Understanding", shadowKeyword: "Intolerance" },
  5: { name: "Fixed Patterns", iChing: "Waiting", hexagram: "☵☰", center: "Sacral", circuit: "Collective", theme: "Universal rhythms and patterns", description: "The Gate of Fixed Patterns is about natural rhythms and the patience to wait for the right timing. People with this gate are deeply connected to universal cycles and patterns. They thrive when they honor their natural rhythms rather than forcing artificial schedules.", giftKeyword: "Patience", shadowKeyword: "Impatience" },
  6: { name: "Friction", iChing: "Conflict", hexagram: "☰☵", center: "SolarPlexus", circuit: "Tribal", theme: "Emotional intimacy", description: "The Gate of Friction is about the emotional wave that governs intimacy and connection. This gate controls access to emotional and physical intimacy. People with this gate experience deep emotional waves that affect their capacity for closeness with others.", giftKeyword: "Diplomacy", shadowKeyword: "Conflict" },
  7: { name: "The Role of the Self", iChing: "The Army", hexagram: "☷☵", center: "G", circuit: "Collective", theme: "Leadership and direction", description: "The Gate of the Role of the Self is about leadership through example. People with this gate have a natural capacity to lead and influence others through their own authentic self-expression. This is democratic leadership that inspires through vision.", giftKeyword: "Virtue", shadowKeyword: "Division" },
  8: { name: "Contribution", iChing: "Holding Together", hexagram: "☵☷", center: "Throat", circuit: "Individual", theme: "Making a unique contribution", description: "The Gate of Contribution is about making a unique and individual contribution to the world. People with this gate feel a deep need to contribute something meaningful and original. This is the energy of the person who says 'I know I can make a difference.'", giftKeyword: "Style", shadowKeyword: "Mediocrity" },
  9: { name: "Focus", iChing: "Taming Power of the Small", hexagram: "☴☰", center: "Sacral", circuit: "Collective", theme: "Determination and focus", description: "The Gate of Focus is about the power of concentration and attention to detail. People with this gate have the ability to focus intensely on the small things that make a big difference. They are natural perfectionists who find satisfaction in mastering details.", giftKeyword: "Determination", shadowKeyword: "Inertia" },
  10: { name: "Behavior of the Self", iChing: "Treading", hexagram: "☰☱", center: "G", circuit: "Individual", theme: "Self-love and behavior", description: "The Gate of the Behavior of the Self is about self-love and authentic behavior. People with this gate are here to love themselves unconditionally and to behave in ways that are true to their nature. This is the foundation of all authentic self-expression.", giftKeyword: "Naturalness", shadowKeyword: "Self-Obsession" },
  11: { name: "Ideas", iChing: "Peace", hexagram: "☷☰", center: "Ajna", circuit: "Collective", theme: "Conceptualization of ideas", description: "The Gate of Ideas is about the stimulation of new ideas and concepts. People with this gate are natural idea generators who are constantly inspired by new possibilities. They see the world through a lens of conceptual understanding.", giftKeyword: "Idealism", shadowKeyword: "Obscurity" },
  12: { name: "Caution", iChing: "Standstill", hexagram: "☰☷", center: "Throat", circuit: "Individual", theme: "Cautious expression", description: "The Gate of Caution governs the timing of social expression. People with this gate know when to speak and when to remain silent. Their expression is deeply emotional and can be profoundly moving when the timing is right.", giftKeyword: "Purity", shadowKeyword: "Vanity" },
  13: { name: "The Listener", iChing: "Fellowship", hexagram: "☰☲", center: "G", circuit: "Collective", theme: "Listening and collecting experiences", description: "The Gate of the Listener is about the ability to listen deeply and collect the stories and experiences of others. People with this gate are natural confidants who others trust with their secrets. They carry the collective memory of human experience.", giftKeyword: "Discernment", shadowKeyword: "Discord" },
  14: { name: "Power Skills", iChing: "Great Possession", hexagram: "☲☰", center: "Sacral", circuit: "Individual", theme: "Empowerment through resources", description: "The Gate of Power Skills is about the ability to empower through material resources and skills. People with this gate have a natural talent for creating abundance and directing resources toward meaningful purposes.", giftKeyword: "Competence", shadowKeyword: "Compromise" },
  15: { name: "Extremes", iChing: "Modesty", hexagram: "☷☶", center: "G", circuit: "Collective", theme: "Love of humanity and extremes", description: "The Gate of Extremes is about the love of humanity expressed through extreme rhythms and patterns. People with this gate swing between extremes in their behavior and lifestyle. They are here to embrace the full spectrum of human experience.", giftKeyword: "Magnetism", shadowKeyword: "Dullness" },
  16: { name: "Skills", iChing: "Enthusiasm", hexagram: "☳☷", center: "Throat", circuit: "Collective", theme: "Mastery through practice", description: "The Gate of Skills is about the enthusiasm for developing mastery through practice and repetition. People with this gate are driven to perfect their skills and share their expertise. They find joy in the process of becoming skilled.", giftKeyword: "Versatility", shadowKeyword: "Indifference" },
  17: { name: "Opinions", iChing: "Following", hexagram: "☱☳", center: "Ajna", circuit: "Collective", theme: "Logical opinions", description: "The Gate of Opinions is about forming and sharing logical opinions. People with this gate have a natural ability to see patterns and form opinions about how things should work. They are here to share their logical perspective.", giftKeyword: "Far-Sightedness", shadowKeyword: "Opinion" },
  18: { name: "Correction", iChing: "Work on the Decayed", hexagram: "☶☴", center: "Spleen", circuit: "Collective", theme: "Intuitive correction", description: "The Gate of Correction is about the intuitive drive to correct and improve patterns. People with this gate have a natural eye for what needs to be fixed or improved. They are the quality controllers of the collective.", giftKeyword: "Integrity", shadowKeyword: "Judgment" },
  19: { name: "Wanting", iChing: "Approach", hexagram: "☷☱", center: "Root", circuit: "Tribal", theme: "Sensitivity to needs", description: "The Gate of Wanting is about sensitivity to the basic needs of the community. People with this gate are deeply attuned to what others need and want. They feel the pressure to ensure that basic needs are met.", giftKeyword: "Sensitivity", shadowKeyword: "Co-Dependence" },
  20: { name: "The Now", iChing: "Contemplation", hexagram: "☴☷", center: "Throat", circuit: "Individual", theme: "Present awareness", description: "The Gate of the Now is about the power of present-moment awareness and contemplation. People with this gate have a natural ability to be fully present and to express what is happening in the moment. This is existential awareness.", giftKeyword: "Self-Assurance", shadowKeyword: "Superficiality" },
  21: { name: "The Hunter", iChing: "Biting Through", hexagram: "☲☳", center: "Heart", circuit: "Tribal", theme: "Control and willpower", description: "The Gate of the Hunter is about the willpower to control resources and outcomes. People with this gate have a strong will and the determination to get what they want. They are natural leaders who take charge of material resources.", giftKeyword: "Authority", shadowKeyword: "Control" },
  22: { name: "Openness", iChing: "Grace", hexagram: "☶☲", center: "SolarPlexus", circuit: "Individual", theme: "Emotional openness and grace", description: "The Gate of Openness is about emotional grace and the ability to listen with an open heart. People with this gate carry a deep emotional sensitivity that, when expressed at the right time, can touch and transform others.", giftKeyword: "Graciousness", shadowKeyword: "Dishonor" },
  23: { name: "Assimilation", iChing: "Splitting Apart", hexagram: "☶☷", center: "Throat", circuit: "Individual", theme: "Expressing individual knowing", description: "The Gate of Assimilation is about the ability to translate individual insights into language that others can understand. People with this gate are here to share unique perspectives that may initially seem strange but carry profound truth.", giftKeyword: "Simplicity", shadowKeyword: "Complexity" },
  24: { name: "Rationalization", iChing: "Return", hexagram: "☷☳", center: "Ajna", circuit: "Individual", theme: "Mental review and reconceptualization", description: "The Gate of Rationalization is about the mental process of reviewing and reconceptualizing ideas. People with this gate experience a constant mental loop of revisiting and refining their understanding until a breakthrough occurs.", giftKeyword: "Invention", shadowKeyword: "Addiction" },
  25: { name: "Innocence", iChing: "Innocence", hexagram: "☰☳", center: "G", circuit: "Individual", theme: "Universal love and spirit", description: "The Gate of Innocence is about the spirit of universal love and acceptance. People with this gate carry a pure, innocent energy that connects them to the divine. They are here to love unconditionally and to trust in the goodness of life.", giftKeyword: "Acceptance", shadowKeyword: "Constriction" },
  26: { name: "The Trickster", iChing: "Great Taming Power", hexagram: "☶☰", center: "Heart", circuit: "Tribal", theme: "Ego and salesmanship", description: "The Gate of the Trickster is about the power of persuasion and the ability to sell ideas, products, or visions. People with this gate have a natural talent for marketing and convincing others of the value of what they offer.", giftKeyword: "Artfulness", shadowKeyword: "Pride" },
  27: { name: "Nourishment", iChing: "Providing Nourishment", hexagram: "☶☳", center: "Sacral", circuit: "Tribal", theme: "Caring and nourishment", description: "The Gate of Nourishment is about the caring energy that nurtures and sustains others. People with this gate have a deep drive to care for and nourish those around them. This is the energy of the caretaker and provider.", giftKeyword: "Selflessness", shadowKeyword: "Selfishness" },
  28: { name: "The Game Player", iChing: "Preponderance of the Great", hexagram: "☱☴", center: "Spleen", circuit: "Individual", theme: "Risk-taking and purpose", description: "The Gate of the Game Player is about the willingness to take risks in pursuit of meaning and purpose. People with this gate are driven to find what is truly worth struggling for. They are existential warriors seeking purpose.", giftKeyword: "Totality", shadowKeyword: "Purposelessness" },
  29: { name: "Perseverance", iChing: "The Abysmal", hexagram: "☵☵", center: "Sacral", circuit: "Collective", theme: "Commitment and saying yes", description: "The Gate of Perseverance is about the power of commitment and the ability to say yes to experiences. People with this gate have a deep capacity for perseverance and dedication once they commit to something.", giftKeyword: "Devotion", shadowKeyword: "Half-Heartedness" },
  30: { name: "Feelings", iChing: "The Clinging Fire", hexagram: "☲☲", center: "SolarPlexus", circuit: "Collective", theme: "Desire and emotional depth", description: "The Gate of Feelings is about the fire of desire and emotional intensity. People with this gate experience deep feelings and desires that drive them to seek new experiences. They are here to feel life fully.", giftKeyword: "Lightness", shadowKeyword: "Desire" },
  31: { name: "Leading", iChing: "Influence", hexagram: "☱☶", center: "Throat", circuit: "Collective", theme: "Democratic leadership", description: "The Gate of Leading is about the ability to influence others through democratic leadership. People with this gate have a natural authority that others recognize and follow. This is leadership through shared vision.", giftKeyword: "Leadership", shadowKeyword: "Arrogance" },
  32: { name: "Continuity", iChing: "Duration", hexagram: "☳☴", center: "Spleen", circuit: "Tribal", theme: "Instinct for what endures", description: "The Gate of Continuity is about the instinctive recognition of what has lasting value. People with this gate can sense what will endure and what will not. They are natural conservators of resources and traditions.", giftKeyword: "Preservation", shadowKeyword: "Failure" },
  33: { name: "Privacy", iChing: "Retreat", hexagram: "☰☶", center: "Throat", circuit: "Collective", theme: "Retreat and reflection", description: "The Gate of Privacy is about the wisdom of retreat and the ability to share experiences through storytelling. People with this gate need periods of withdrawal to process their experiences before sharing them.", giftKeyword: "Mindfulness", shadowKeyword: "Forgetting" },
  34: { name: "Power", iChing: "Great Power", hexagram: "☳☰", center: "Sacral", circuit: "Individual", theme: "Pure sacral power", description: "The Gate of Power is about raw sacral energy and the power to act. People with this gate carry tremendous life force energy that seeks expression through action. This is pure, individual power that must be used correctly.", giftKeyword: "Strength", shadowKeyword: "Force" },
  35: { name: "Change", iChing: "Progress", hexagram: "☲☷", center: "Throat", circuit: "Collective", theme: "Progress through experience", description: "The Gate of Change is about the desire for new experiences and progress. People with this gate are driven to explore and experience everything life has to offer. They are the adventurers of the collective.", giftKeyword: "Adventure", shadowKeyword: "Hunger" },
  36: { name: "Crisis", iChing: "Darkening of the Light", hexagram: "☷☲", center: "SolarPlexus", circuit: "Collective", theme: "Emotional crisis and growth", description: "The Gate of Crisis is about the emotional experience of crisis as a catalyst for growth. People with this gate are drawn to intense emotional experiences that ultimately lead to wisdom and compassion.", giftKeyword: "Humanity", shadowKeyword: "Turbulence" },
  37: { name: "Friendship", iChing: "The Family", hexagram: "☴☲", center: "SolarPlexus", circuit: "Tribal", theme: "Community and friendship", description: "The Gate of Friendship is about the emotional bonds that create community and family. People with this gate are natural community builders who create strong bonds through emotional connection and shared values.", giftKeyword: "Equality", shadowKeyword: "Weakness" },
  38: { name: "The Fighter", iChing: "Opposition", hexagram: "☲☱", center: "Root", circuit: "Individual", theme: "Fighting for purpose", description: "The Gate of the Fighter is about the pressure to fight for individual purpose and meaning. People with this gate are driven by an inner fire to find and defend what truly matters. They are spiritual warriors.", giftKeyword: "Perseverance", shadowKeyword: "Struggle" },
  39: { name: "Provocation", iChing: "Obstruction", hexagram: "☵☶", center: "Root", circuit: "Individual", theme: "Provoking spirit", description: "The Gate of Provocation is about the pressure to provoke emotional responses in others to awaken their spirit. People with this gate have a natural ability to push others' buttons in ways that ultimately serve growth.", giftKeyword: "Dynamism", shadowKeyword: "Provocation" },
  40: { name: "Aloneness", iChing: "Deliverance", hexagram: "☳☵", center: "Heart", circuit: "Tribal", theme: "Willpower and aloneness", description: "The Gate of Aloneness is about the need for solitude to restore willpower. People with this gate need regular periods of alone time to recharge their ego energy. They serve the community best when they honor their need for space.", giftKeyword: "Resolve", shadowKeyword: "Exhaustion" },
  41: { name: "Contraction", iChing: "Decrease", hexagram: "☶☱", center: "Root", circuit: "Collective", theme: "Imagination and desire", description: "The Gate of Contraction is about the pressure of desire and imagination. People with this gate feel a constant pressure to imagine new possibilities and experiences. This is the starting point of all human experience.", giftKeyword: "Anticipation", shadowKeyword: "Fantasy" },
  42: { name: "Growth", iChing: "Increase", hexagram: "☴☳", center: "Sacral", circuit: "Collective", theme: "Growth and completion", description: "The Gate of Growth is about the energy to bring things to completion and maximize growth. People with this gate have the sacral energy to see things through to their natural conclusion.", giftKeyword: "Detachment", shadowKeyword: "Expectation" },
  43: { name: "Insight", iChing: "Breakthrough", hexagram: "☱☰", center: "Ajna", circuit: "Individual", theme: "Mental breakthrough", description: "The Gate of Insight is about sudden mental breakthroughs and unique knowing. People with this gate experience flashes of insight that come from a deep inner knowing. Their insights are individual and often ahead of their time.", giftKeyword: "Insight", shadowKeyword: "Deafness" },
  44: { name: "Alertness", iChing: "Coming to Meet", hexagram: "☰☴", center: "Spleen", circuit: "Tribal", theme: "Instinctive alertness", description: "The Gate of Alertness is about the instinctive ability to recognize patterns and potential. People with this gate have a keen sense for what will work in the material world. They can smell success and opportunity.", giftKeyword: "Teamwork", shadowKeyword: "Interference" },
  45: { name: "The Gatherer", iChing: "Gathering Together", hexagram: "☱☷", center: "Throat", circuit: "Tribal", theme: "Gathering resources", description: "The Gate of the Gatherer is about the ability to gather and distribute resources. People with this gate are natural leaders who bring people together around shared material goals. This is the energy of the king or queen.", giftKeyword: "Synergy", shadowKeyword: "Dominance" },
  46: { name: "Determination", iChing: "Pushing Upward", hexagram: "☷☴", center: "G", circuit: "Collective", theme: "Love of the body", description: "The Gate of Determination is about the love of the physical body and the determination to succeed through embodiment. People with this gate are deeply connected to their physical experience and find success through being in the right place at the right time.", giftKeyword: "Delight", shadowKeyword: "Seriousness" },
  47: { name: "Realization", iChing: "Oppression", hexagram: "☱☵", center: "Ajna", circuit: "Collective", theme: "Making sense of the abstract", description: "The Gate of Realization is about the mental process of making sense of abstract experiences. People with this gate are constantly trying to understand and articulate what they have experienced. This is the aha moment.", giftKeyword: "Transmutation", shadowKeyword: "Oppression" },
  48: { name: "Depth", iChing: "The Well", hexagram: "☵☴", center: "Spleen", circuit: "Collective", theme: "Depth of knowledge", description: "The Gate of Depth is about the deep well of knowledge and the fear of inadequacy. People with this gate have access to profound depth of understanding but may fear they don't know enough. When they trust their depth, they become masterful.", giftKeyword: "Resourcefulness", shadowKeyword: "Inadequacy" },
  49: { name: "Revolution", iChing: "Revolution", hexagram: "☱☲", center: "SolarPlexus", circuit: "Tribal", theme: "Emotional revolution", description: "The Gate of Revolution is about the emotional power to accept or reject, to revolutionize or maintain the status quo. People with this gate have the emotional sensitivity to know when change is needed in relationships and communities.", giftKeyword: "Revolution", shadowKeyword: "Reaction" },
  50: { name: "Values", iChing: "The Cauldron", hexagram: "☲☴", center: "Spleen", circuit: "Tribal", theme: "Tribal values and laws", description: "The Gate of Values is about establishing and maintaining the values and laws that protect the community. People with this gate are the guardians of tribal values and have a deep sense of responsibility for others.", giftKeyword: "Equilibrium", shadowKeyword: "Corruption" },
  51: { name: "Shock", iChing: "The Arousing", hexagram: "☳☳", center: "Heart", circuit: "Individual", theme: "Competitive spirit and shock", description: "The Gate of Shock is about the willpower to compete and the ability to shock others into awakening. People with this gate are spiritual warriors who use the element of surprise to initiate others into new levels of awareness.", giftKeyword: "Initiative", shadowKeyword: "Agitation" },
  52: { name: "Stillness", iChing: "Keeping Still", hexagram: "☶☶", center: "Root", circuit: "Collective", theme: "Concentration and stillness", description: "The Gate of Stillness is about the pressure to be still and concentrate. People with this gate have the ability to sit still and focus deeply, creating a foundation of calm concentration that supports detailed work.", giftKeyword: "Restraint", shadowKeyword: "Stress" },
  53: { name: "Beginnings", iChing: "Development", hexagram: "☴☶", center: "Root", circuit: "Collective", theme: "Starting new cycles", description: "The Gate of Beginnings is about the pressure to start new things and initiate new cycles. People with this gate feel a constant drive to begin new projects, experiences, and phases of life.", giftKeyword: "Expansion", shadowKeyword: "Immaturity" },
  54: { name: "Ambition", iChing: "The Marrying Maiden", hexagram: "☳☱", center: "Root", circuit: "Tribal", theme: "Drive and ambition", description: "The Gate of Ambition is about the pressure to rise in the material world through ambition and drive. People with this gate are naturally ambitious and driven to improve their position in the tribal hierarchy.", giftKeyword: "Aspiration", shadowKeyword: "Greed" },
  55: { name: "Spirit", iChing: "Abundance", hexagram: "☳☲", center: "SolarPlexus", circuit: "Individual", theme: "Emotional spirit and abundance", description: "The Gate of Spirit is about the emotional depth that connects to spiritual abundance. People with this gate carry a deep emotional sensitivity that can access states of profound spiritual richness and melancholy.", giftKeyword: "Freedom", shadowKeyword: "Victimization" },
  56: { name: "Stimulation", iChing: "The Wanderer", hexagram: "☲☶", center: "Throat", circuit: "Collective", theme: "Storytelling and stimulation", description: "The Gate of Stimulation is about the ability to stimulate others through storytelling and the sharing of experiences. People with this gate are natural storytellers who bring ideas to life through vivid narrative.", giftKeyword: "Enrichment", shadowKeyword: "Distraction" },
  57: { name: "Intuition", iChing: "The Gentle", hexagram: "☴☴", center: "Spleen", circuit: "Individual", theme: "Intuitive clarity", description: "The Gate of Intuition is about the most penetrating form of awareness - intuitive clarity in the present moment. People with this gate have access to a gentle but powerful intuitive knowing that operates in the now.", giftKeyword: "Intuition", shadowKeyword: "Unease" },
  58: { name: "Vitality", iChing: "The Joyous", hexagram: "☱☱", center: "Root", circuit: "Collective", theme: "Joy and vitality", description: "The Gate of Vitality is about the pressure to find joy and vitality in life. People with this gate are driven to correct and improve things in order to create more joy and aliveness in the world.", giftKeyword: "Vitality", shadowKeyword: "Dissatisfaction" },
  59: { name: "Sexuality", iChing: "Dispersion", hexagram: "☴☵", center: "Sacral", circuit: "Tribal", theme: "Intimacy and fertility", description: "The Gate of Sexuality is about the sacral energy of intimacy, fertility, and breaking down barriers between people. People with this gate have a powerful energy for creating intimate bonds and new life.", giftKeyword: "Intimacy", shadowKeyword: "Dishonesty" },
  60: { name: "Limitation", iChing: "Limitation", hexagram: "☵☱", center: "Root", circuit: "Individual", theme: "Acceptance of limitation", description: "The Gate of Limitation is about the pressure to accept and transcend limitations. People with this gate understand that true freedom comes through accepting limitations and working within constraints to create something new.", giftKeyword: "Realism", shadowKeyword: "Limitation" },
  61: { name: "Mystery", iChing: "Inner Truth", hexagram: "☴☱", center: "Head", circuit: "Individual", theme: "Inner truth and mystery", description: "The Gate of Mystery is about the pressure to know the unknowable and to penetrate the mysteries of existence. People with this gate are driven by a deep need to understand the fundamental truths of life.", giftKeyword: "Inspiration", shadowKeyword: "Psychosis" },
  62: { name: "Detail", iChing: "Preponderance of the Small", hexagram: "☳☶", center: "Throat", circuit: "Collective", theme: "Expressing details", description: "The Gate of Detail is about the ability to express and communicate details precisely. People with this gate have a talent for naming things accurately and communicating factual information clearly.", giftKeyword: "Precision", shadowKeyword: "Intellect" },
  63: { name: "Doubt", iChing: "After Completion", hexagram: "☵☲", center: "Head", circuit: "Collective", theme: "Logical doubt and questioning", description: "The Gate of Doubt is about the mental pressure to question and doubt in order to find logical answers. People with this gate are driven by a need to verify and validate through logical inquiry.", giftKeyword: "Inquiry", shadowKeyword: "Doubt" },
  64: { name: "Confusion", iChing: "Before Completion", hexagram: "☲☵", center: "Head", circuit: "Collective", theme: "Mental pressure to make sense", description: "The Gate of Confusion is about the mental pressure to make sense of past experiences. People with this gate experience a constant stream of mental images and memories that seek resolution and understanding.", giftKeyword: "Imagination", shadowKeyword: "Confusion" },
};

// ─── Channel Descriptions ─────────────────────────────────────────────────────

export const CHANNEL_DESCRIPTIONS: Record<string, {
  name: string;
  gates: [number, number];
  centers: [string, string];
  circuit: string;
  theme: string;
  description: string;
}> = {
  "64-47": { name: "Channel of Abstraction", gates: [64, 47], centers: ["Head", "Ajna"], circuit: "Collective", theme: "Mental activity mixed with clarity", description: "This channel creates a constant mental process of reviewing past experiences and making sense of them. People with this channel are abstract thinkers who process life through mental images and eventually arrive at profound realizations." },
  "61-24": { name: "Channel of Awareness", gates: [61, 24], centers: ["Head", "Ajna"], circuit: "Individual", theme: "A thinker from inspiration to concept", description: "This channel connects the pressure to know the unknowable with the mental process of rationalization. People with this channel are deep thinkers who receive inspirations and then work to conceptualize them into understanding." },
  "63-4": { name: "Channel of Logic", gates: [63, 4], centers: ["Head", "Ajna"], circuit: "Collective", theme: "Mental ease mixed with doubt", description: "This channel creates the logical mind that questions everything and seeks formulas and patterns. People with this channel are natural scientists and logicians who need to understand the underlying patterns of life." },
  "17-62": { name: "Channel of Acceptance", gates: [17, 62], centers: ["Ajna", "Throat"], circuit: "Collective", theme: "Organizational being", description: "This channel connects logical opinions with detailed expression. People with this channel are natural organizers who can articulate logical patterns and share their understanding in a structured, detailed way." },
  "43-23": { name: "Channel of Structuring", gates: [43, 23], centers: ["Ajna", "Throat"], circuit: "Individual", theme: "Individuality from genius to freak", description: "This channel connects individual insight with the ability to express it. People with this channel have unique mental breakthroughs that they can articulate, though their ideas may seem strange or ahead of their time." },
  "11-56": { name: "Channel of Curiosity", gates: [11, 56], centers: ["Ajna", "Throat"], circuit: "Collective", theme: "A searcher and storyteller", description: "This channel connects ideas with the ability to stimulate through storytelling. People with this channel are natural storytellers and teachers who share their ideas and experiences in engaging ways." },
  "48-16": { name: "Channel of The Wavelength", gates: [48, 16], centers: ["Spleen", "Throat"], circuit: "Collective", theme: "Talent through depth", description: "This channel connects deep knowledge with the enthusiasm to express it as skill. People with this channel develop mastery through depth of understanding and enthusiastic practice." },
  "57-20": { name: "Channel of The Brainwave", gates: [57, 20], centers: ["Spleen", "Throat"], circuit: "Individual", theme: "Penetrating awareness in the now", description: "This channel connects intuitive clarity with present-moment awareness. People with this channel have a powerful intuitive knowing that they can express spontaneously in the moment." },
  "34-20": { name: "Channel of Charisma", gates: [34, 20], centers: ["Sacral", "Throat"], circuit: "Individual", theme: "Where thoughts must become deeds", description: "This channel connects pure sacral power with present-moment expression. People with this channel are charismatic beings who act and speak from a place of pure response and power." },
  "10-20": { name: "Channel of Awakening", gates: [10, 20], centers: ["G", "Throat"], circuit: "Individual", theme: "Commitment to higher principles", description: "This channel connects self-love with present-moment awareness. People with this channel are here to awaken to their true nature and express their authentic self in every moment." },
  "7-31": { name: "Channel of The Alpha", gates: [7, 31], centers: ["G", "Throat"], circuit: "Collective", theme: "Leadership for good or not", description: "This channel connects the role of the self with the ability to lead through influence. People with this channel are natural democratic leaders who can guide others toward a shared vision." },
  "1-8": { name: "Channel of Inspiration", gates: [1, 8], centers: ["G", "Throat"], circuit: "Individual", theme: "Creative role model", description: "This channel connects creative self-expression with the drive to contribute. People with this channel are creative role models who inspire others through their unique and original contributions." },
  "13-33": { name: "Channel of The Prodigal", gates: [13, 33], centers: ["G", "Throat"], circuit: "Collective", theme: "A witness through reflection", description: "This channel connects listening with the wisdom of retreat. People with this channel are natural witnesses who collect experiences and share them as wisdom through reflection and storytelling." },
  "45-21": { name: "Channel of Money", gates: [45, 21], centers: ["Throat", "Heart"], circuit: "Tribal", theme: "A materialist and controller", description: "This channel connects the gatherer with the hunter. People with this channel have a powerful drive to control and manage material resources. They are natural leaders in business and finance." },
  "12-22": { name: "Channel of Openness", gates: [12, 22], centers: ["Throat", "SolarPlexus"], circuit: "Individual", theme: "A social being", description: "This channel connects cautious expression with emotional openness. People with this channel are deeply emotional social beings who can profoundly move others when they express at the right time." },
  "35-36": { name: "Channel of Transitoriness", gates: [35, 36], centers: ["Throat", "SolarPlexus"], circuit: "Collective", theme: "A jack of all trades", description: "This channel connects the desire for new experiences with emotional crisis. People with this channel are experiential beings who learn through emotional depth and the full range of human experience." },
  "10-34": { name: "Channel of Exploration", gates: [10, 34], centers: ["G", "Sacral"], circuit: "Individual", theme: "Following one's convictions", description: "This channel connects self-love with pure power. People with this channel are explorers who follow their own convictions with tremendous energy and determination." },
  "10-57": { name: "Channel of Perfected Form", gates: [10, 57], centers: ["G", "Spleen"], circuit: "Individual", theme: "Survival through intuitive behavior", description: "This channel connects self-love with intuition. People with this channel have an intuitive sense of how to behave authentically, creating a perfected form of self-expression." },
  "25-51": { name: "Channel of Initiation", gates: [25, 51], centers: ["G", "Heart"], circuit: "Individual", theme: "Needing to be first", description: "This channel connects innocence with the competitive spirit. People with this channel are spiritual warriors who initiate others through shock and the power of their innocent spirit." },
  "15-5": { name: "Channel of Rhythm", gates: [15, 5], centers: ["G", "Sacral"], circuit: "Collective", theme: "Being in the flow", description: "This channel connects extremes with fixed patterns. People with this channel are deeply connected to natural rhythms and find their power when they flow with life's natural cycles." },
  "46-29": { name: "Channel of Discovery", gates: [46, 29], centers: ["G", "Sacral"], circuit: "Collective", theme: "Succeeding where others fail", description: "This channel connects determination with perseverance. People with this channel have a remarkable ability to commit to experiences and succeed through their physical determination." },
  "2-14": { name: "Channel of The Beat", gates: [2, 14], centers: ["G", "Sacral"], circuit: "Individual", theme: "Keeper of keys", description: "This channel connects higher direction with power skills. People with this channel are empowered beings who know their direction and have the resources to follow it." },
  "26-44": { name: "Channel of Surrender", gates: [26, 44], centers: ["Heart", "Spleen"], circuit: "Tribal", theme: "A transmitter", description: "This channel connects the trickster with alertness. People with this channel are natural salespeople and transmitters who can sense what will succeed and persuade others of its value." },
  "40-37": { name: "Channel of Community", gates: [40, 37], centers: ["Heart", "SolarPlexus"], circuit: "Tribal", theme: "A part seeking a whole", description: "This channel connects aloneness with friendship. People with this channel are community builders who balance their need for solitude with their deep emotional bonds to family and community." },
  "59-6": { name: "Channel of Mating", gates: [59, 6], centers: ["Sacral", "SolarPlexus"], circuit: "Tribal", theme: "Focused on reproduction", description: "This channel connects sexuality with emotional intimacy. People with this channel carry a powerful energy for creating intimate bonds and new life through emotional and physical connection." },
  "27-50": { name: "Channel of Preservation", gates: [27, 50], centers: ["Sacral", "Spleen"], circuit: "Tribal", theme: "A custodian", description: "This channel connects nourishment with values. People with this channel are natural custodians who care for others while maintaining the values and standards that protect the community." },
  "42-53": { name: "Channel of Maturation", gates: [42, 53], centers: ["Sacral", "Root"], circuit: "Collective", theme: "Balanced development", description: "This channel connects growth with beginnings. People with this channel have the energy to start new cycles and see them through to completion, creating balanced development." },
  "3-60": { name: "Channel of Mutation", gates: [3, 60], centers: ["Sacral", "Root"], circuit: "Individual", theme: "Energy which initiates and fluctuates", description: "This channel connects ordering with limitation. People with this channel carry the energy of mutation - the ability to bring new order out of chaos within the constraints of limitation." },
  "9-52": { name: "Channel of Concentration", gates: [9, 52], centers: ["Sacral", "Root"], circuit: "Collective", theme: "Determination and focus", description: "This channel connects focus with stillness. People with this channel have a remarkable ability to concentrate and focus their energy on detailed work with patience and determination." },
  "54-32": { name: "Channel of Transformation", gates: [54, 32], centers: ["Root", "Spleen"], circuit: "Tribal", theme: "Being driven", description: "This channel connects ambition with continuity. People with this channel are driven to transform their position in the world through instinctive recognition of what has lasting value." },
  "38-28": { name: "Channel of Struggle", gates: [38, 28], centers: ["Root", "Spleen"], circuit: "Individual", theme: "Stubbornness", description: "This channel connects the fighter with the game player. People with this channel are stubborn warriors who struggle to find meaning and purpose, never giving up on what matters." },
  "58-18": { name: "Channel of Judgment", gates: [58, 18], centers: ["Root", "Spleen"], circuit: "Collective", theme: "Insatiability", description: "This channel connects vitality with correction. People with this channel are driven to correct and improve patterns, finding joy in making things better and more vital." },
  "34-57": { name: "Channel of Power", gates: [34, 57], centers: ["Sacral", "Spleen"], circuit: "Individual", theme: "An archetype", description: "This channel connects pure power with intuition. People with this channel are powerful, intuitive beings who act from a deep instinctive knowing. This is one of the most powerful channels in the bodygraph." },
  "19-49": { name: "Channel of Synthesis", gates: [19, 49], centers: ["Root", "SolarPlexus"], circuit: "Tribal", theme: "Sensitivity", description: "This channel connects wanting with revolution. People with this channel are deeply sensitive to the needs of the community and have the emotional power to revolutionize how those needs are met." },
  "39-55": { name: "Channel of Emoting", gates: [39, 55], centers: ["Root", "SolarPlexus"], circuit: "Individual", theme: "Moodiness", description: "This channel connects provocation with spirit. People with this channel experience deep emotional waves that swing between melancholy and ecstasy, provoking spiritual growth." },
  "41-30": { name: "Channel of Recognition", gates: [41, 30], centers: ["Root", "SolarPlexus"], circuit: "Collective", theme: "Focused energy and feelings", description: "This channel connects imagination with feelings. People with this channel are driven by desire and imagination to seek new experiences that create deep emotional recognition and fulfillment." },
};

// ─── Center Descriptions ──────────────────────────────────────────────────────

export const CENTER_DESCRIPTIONS: Record<string, {
  name: string;
  biologicalCorrelation: string;
  theme: string;
  definedMeaning: string;
  openMeaning: string;
  notSelfQuestion: string;
}> = {
  Head: { name: "Head Center", biologicalCorrelation: "Pineal Gland", theme: "Inspiration & Mental Pressure", definedMeaning: "You have a consistent source of inspiration and mental pressure. You are designed to inspire others with your questions and ideas.", openMeaning: "You are open to all kinds of inspiration and mental pressure from others. You may feel overwhelmed by questions that are not your own.", notSelfQuestion: "Am I trying to answer everyone else's questions?" },
  Ajna: { name: "Ajna Center", biologicalCorrelation: "Anterior & Posterior Pituitary", theme: "Conceptualization & Mental Awareness", definedMeaning: "You have a fixed and reliable way of processing information and forming concepts. Your mental processes are consistent.", openMeaning: "You have a flexible mind that can see things from many perspectives. You may struggle with mental certainty.", notSelfQuestion: "Am I trying to convince everyone that I am certain?" },
  Throat: { name: "Throat Center", biologicalCorrelation: "Thyroid & Parathyroid", theme: "Communication & Manifestation", definedMeaning: "You have a consistent way of communicating and manifesting. Your voice and expression are reliable and defined.", openMeaning: "You have a flexible voice that can adapt to different situations. You may feel pressure to speak or act when it's not the right time.", notSelfQuestion: "Am I trying to attract attention?" },
  G: { name: "G Center (Self)", biologicalCorrelation: "Liver & Blood", theme: "Identity, Direction & Love", definedMeaning: "You have a fixed sense of identity, direction, and love. You know who you are and where you're going.", openMeaning: "You are open to different identities and directions. You may search for your identity and direction through others.", notSelfQuestion: "Am I still looking for love and direction?" },
  Heart: { name: "Heart Center (Ego/Will)", biologicalCorrelation: "Heart, Stomach, Gallbladder, Thymus", theme: "Willpower & Material World", definedMeaning: "You have consistent willpower and access to ego energy. You can make and keep promises reliably.", openMeaning: "You do not have consistent willpower. You may overcompensate by trying to prove your worth or making promises you can't keep.", notSelfQuestion: "Do I have something to prove?" },
  Sacral: { name: "Sacral Center", biologicalCorrelation: "Ovaries & Testes", theme: "Life Force, Sexuality & Work", definedMeaning: "You have a powerful and consistent life force energy. You are designed to respond to life and have sustainable energy for work.", openMeaning: "You do not have consistent sacral energy. You may not know when enough is enough and can burn out by trying to keep up with others.", notSelfQuestion: "Do I know when enough is enough?" },
  SolarPlexus: { name: "Solar Plexus Center", biologicalCorrelation: "Kidneys, Prostate, Pancreas, Nervous System", theme: "Emotions, Feelings & Sensitivity", definedMeaning: "You have a defined emotional wave. You experience consistent emotional highs and lows. Emotional clarity comes over time, never in the moment.", openMeaning: "You amplify the emotions of others. You may avoid confrontation and truth to keep the peace.", notSelfQuestion: "Am I avoiding confrontation and truth?" },
  Spleen: { name: "Spleen Center", biologicalCorrelation: "Spleen, Lymphatic System", theme: "Intuition, Health & Survival", definedMeaning: "You have consistent access to intuitive awareness about health, safety, and well-being. Your intuition speaks once and quietly.", openMeaning: "You amplify others' fears and may hold onto things (people, jobs, habits) that are not healthy for you.", notSelfQuestion: "Am I holding on to what is not good for me?" },
  Root: { name: "Root Center", biologicalCorrelation: "Adrenal Glands", theme: "Adrenaline, Pressure & Drive", definedMeaning: "You have a consistent way of dealing with pressure and stress. You can handle pressure without being overwhelmed.", openMeaning: "You amplify the pressure from others and may feel constantly rushed or under stress. You may try to get things done quickly to relieve the pressure.", notSelfQuestion: "Am I in a hurry to get things done so I can be free of the pressure?" },
};

// ─── Type Descriptions ────────────────────────────────────────────────────────

export const TYPE_DESCRIPTIONS: Record<string, {
  name: string;
  percentage: string;
  strategy: string;
  signature: string;
  notSelf: string;
  aura: string;
  description: string;
  strengths: string[];
  challenges: string[];
}> = {
  Manifestor: { name: "Manifestor", percentage: "~8%", strategy: "To Inform", signature: "Peace", notSelf: "Anger", aura: "Closed and Repelling", description: "Manifestors are the initiators of the Human Design system. They are the only type designed to act independently without waiting. Their closed and repelling aura gives them the ability to push through resistance and make things happen. When Manifestors inform those who will be affected by their actions, they find peace instead of anger.", strengths: ["Natural initiators", "Independent action", "Powerful impact", "Visionary leadership"], challenges: ["Feeling controlled", "Remembering to inform", "Finding peace with rest", "Dealing with resistance"] },
  Generator: { name: "Generator", percentage: "~37%", strategy: "To Respond", signature: "Satisfaction", notSelf: "Frustration", aura: "Open and Enveloping", description: "Generators are the life force of the planet. They have a defined Sacral center that gives them sustainable energy for work they love. Their open and enveloping aura draws life to them. When Generators wait to respond to what life brings them, they find deep satisfaction. When they initiate, they experience frustration.", strengths: ["Sustainable energy", "Mastery through response", "Magnetic aura", "Deep satisfaction in work"], challenges: ["Waiting to respond", "Not initiating", "Knowing when to quit", "Patience with the process"] },
  "Manifesting Generator": { name: "Manifesting Generator", percentage: "~33%", strategy: "To Respond, Then Inform", signature: "Satisfaction", notSelf: "Frustration & Anger", aura: "Open and Enveloping", description: "Manifesting Generators combine the life force of the Generator with the initiating power of the Manifestor. They are multi-passionate beings who move quickly and efficiently. Their strategy is to wait to respond, then inform before acting. They are designed to skip steps and find shortcuts.", strengths: ["Multi-passionate", "Fast and efficient", "Powerful energy", "Natural multi-taskers"], challenges: ["Slowing down to respond", "Informing before acting", "Completing what they start", "Not skipping important steps"] },
  Projector: { name: "Projector", percentage: "~20%", strategy: "Wait for the Invitation", signature: "Success", notSelf: "Bitterness", aura: "Focused and Absorbing", description: "Projectors are the guides and advisors of the Human Design system. Their focused and absorbing aura allows them to see deeply into others. They are designed to wait for recognition and invitation before sharing their wisdom. When recognized and invited, Projectors experience deep success.", strengths: ["Deep insight into others", "Natural guides", "Efficient energy use", "Wisdom and mastery"], challenges: ["Waiting for invitation", "Managing energy", "Not giving unsolicited advice", "Dealing with bitterness"] },
  Reflector: { name: "Reflector", percentage: "~1%", strategy: "Wait a Lunar Cycle", signature: "Surprise", notSelf: "Disappointment", aura: "Resistant and Sampling", description: "Reflectors are the rarest type, with no defined centers. They are the mirrors of the community, reflecting the health and well-being of their environment. Their strategy is to wait a full lunar cycle (28 days) before making major decisions. When they honor this process, they experience the surprise of life.", strengths: ["Community barometer", "Unique perspective", "Wisdom of the moon", "Openness to all experience"], challenges: ["Finding the right environment", "28-day decision process", "Not identifying with others", "Dealing with inconsistency"] },
};

// ─── Authority Descriptions ───────────────────────────────────────────────────

export const AUTHORITY_DESCRIPTIONS: Record<string, {
  name: string;
  description: string;
  howToUse: string;
}> = {
  "Emotional (Solar Plexus)": { name: "Emotional Authority", description: "You have a defined Solar Plexus center, which means you experience an emotional wave. Your truth is never in the moment - it reveals itself over time as you ride your emotional wave from high to low and back again.", howToUse: "Never make important decisions in the heat of the moment, whether you're feeling high or low. Wait for emotional clarity - a sense of calm knowing that comes after you've experienced the full range of your emotional wave. Sleep on important decisions. The mantra is: 'There is no truth in the now.'" },
  "Sacral": { name: "Sacral Authority", description: "Your Sacral center is your decision-making authority. It communicates through gut responses - sounds like 'uh-huh' (yes) or 'uhn-uhn' (no), and physical sensations of expansion or contraction.", howToUse: "Pay attention to your gut response when life presents you with opportunities. Ask yourself yes/no questions and notice your body's response. Your Sacral speaks in the moment through sounds and physical sensations. Trust the initial gut response - it knows before your mind does." },
  "Splenic": { name: "Splenic Authority", description: "Your Spleen center is your decision-making authority. It communicates through spontaneous intuitive hits - a quiet inner knowing about what is healthy and safe for you in the moment.", howToUse: "Trust your first instinct. The Spleen speaks only once, quietly and in the moment. It's a subtle awareness that something is right or wrong for you. Don't overthink it - your splenic awareness is faster than your mind. Pay attention to spontaneous feelings of attraction or repulsion." },
  "Ego Manifested": { name: "Ego Manifested Authority", description: "Your Heart/Ego center is connected to the Throat, giving you the authority to make decisions based on what your heart truly wants and can commit to.", howToUse: "Listen to what you truly want and what you're willing to commit your willpower to. Ask yourself: 'Is this what I really want? Am I willing to put my heart into this?' Your decisions should come from genuine desire and willpower, not obligation." },
  "Ego Projected": { name: "Ego Projected Authority", description: "Your Heart/Ego center is your authority, but it projects through the G center rather than the Throat. You need to hear yourself talk about what you want to find clarity.", howToUse: "Talk to trusted friends about your decisions and listen to what comes out of your mouth. You'll hear your truth in your own words. Pay attention to what excites your heart and what you feel genuinely willing to commit to." },
  "Self-Projected": { name: "Self-Projected Authority", description: "Your G center (Self) is your decision-making authority. You find clarity by hearing yourself speak about your identity and direction.", howToUse: "Talk to trusted people about your decisions and listen to what you say. Your truth emerges through your own voice. Pay attention to statements about identity ('I am...') and direction ('I'm going to...'). Your decisions should align with your sense of self." },
  "Mental (Outer Authority)": { name: "Mental/Environmental Authority", description: "You have no inner authority below the Throat. Your decision-making process involves talking things through with others and being in the right environment.", howToUse: "Discuss your decisions with different people and in different environments. Notice how different places and people affect your clarity. You are designed to be a sounding board for others, and in turn, you find your own clarity through dialogue and environment." },
  "Lunar (No Inner Authority)": { name: "Lunar Authority", description: "As a Reflector with no defined centers, your authority is connected to the Moon's 28-day cycle. You need a full lunar cycle to gain clarity on major decisions.", howToUse: "For important decisions, wait a full 28-day lunar cycle. During this time, discuss the decision with different people and notice how your perspective shifts day by day. Keep a moon journal. After the full cycle, you'll have a clear sense of what's right for you." },
};

// ─── Profile Descriptions ─────────────────────────────────────────────────────

export const PROFILE_DESCRIPTIONS: Record<string, {
  name: string;
  theme: string;
  description: string;
  conscious: string;
  unconscious: string;
}> = {
  "1/3": { name: "Investigator / Martyr", theme: "Foundation through trial and error", description: "The 1/3 profile combines the need for a solid foundation of knowledge with learning through direct experience. You are here to investigate deeply and then test what you've learned through trial and error. Your life is a journey of discovery through both study and experience.", conscious: "Line 1 (Investigator): You need to feel secure through deep knowledge and understanding. You research thoroughly before committing.", unconscious: "Line 3 (Martyr): You learn through trial and error, discovering what works and what doesn't through direct experience." },
  "1/4": { name: "Investigator / Opportunist", theme: "Foundation through networking", description: "The 1/4 profile combines deep investigation with the power of personal networks. You build a solid foundation of knowledge and then share it through your close relationships. Opportunities come through people you know.", conscious: "Line 1 (Investigator): You need thorough understanding and a secure foundation before moving forward.", unconscious: "Line 4 (Opportunist): Your opportunities and influence come through your personal network and close relationships." },
  "2/4": { name: "Hermit / Opportunist", theme: "Natural talent shared through networks", description: "The 2/4 profile combines natural talent with the power of relationships. You have innate gifts that others can see, even when you can't. Your talents are called out and shared through your personal network.", conscious: "Line 2 (Hermit): You have natural talents and need alone time to develop them. You may not see your own gifts.", unconscious: "Line 4 (Opportunist): Your opportunities come through your network. Others recognize and call out your talents." },
  "2/5": { name: "Hermit / Heretic", theme: "Natural talent with universal impact", description: "The 2/5 profile combines natural talent with the ability to offer practical solutions to others. You have innate gifts and are projected upon as someone who can solve problems. Your challenge is managing expectations.", conscious: "Line 2 (Hermit): You have natural talents and need solitude to develop them.", unconscious: "Line 5 (Heretic): Others project their expectations onto you. You have the potential to offer universal solutions." },
  "3/5": { name: "Martyr / Heretic", theme: "Trial and error with universal impact", description: "The 3/5 profile combines experiential learning with the ability to offer practical solutions. You learn through trial and error and then share your hard-won wisdom as universal solutions.", conscious: "Line 3 (Martyr): You learn through direct experience, discovering what works through trial and error.", unconscious: "Line 5 (Heretic): Others project expectations onto you. Your experiences become universal lessons." },
  "3/6": { name: "Martyr / Role Model", theme: "Trial and error becoming wisdom", description: "The 3/6 profile combines experiential learning with the potential for wisdom and role modeling. Your life has three phases: experimentation (0-30), withdrawal and observation (30-50), and becoming a role model (50+).", conscious: "Line 3 (Martyr): You learn through trial and error, especially in the first phase of life.", unconscious: "Line 6 (Role Model): You are here to eventually become a living example of wisdom gained through experience." },
  "4/6": { name: "Opportunist / Role Model", theme: "Influence through networks becoming wisdom", description: "The 4/6 profile combines the power of personal networks with the journey toward role model wisdom. Your influence comes through relationships, and over time you develop into a wise guide.", conscious: "Line 4 (Opportunist): Your opportunities and influence come through your personal network.", unconscious: "Line 6 (Role Model): You go through three life phases, eventually becoming a role model of wisdom." },
  "4/1": { name: "Opportunist / Investigator", theme: "Fixed fate through networks and knowledge", description: "The 4/1 profile is the only 'fixed fate' profile. You combine the power of personal networks with a deep foundation of knowledge. Your path is relatively fixed, and your influence comes through sharing your deep knowledge within your network.", conscious: "Line 4 (Opportunist): Your opportunities come through your personal network and relationships.", unconscious: "Line 1 (Investigator): You have a deep, unconscious need for a solid foundation of knowledge." },
  "5/1": { name: "Heretic / Investigator", theme: "Universal solutions through deep knowledge", description: "The 5/1 profile combines the ability to offer universal solutions with a deep foundation of investigation. Others project their expectations onto you, and your thorough knowledge base allows you to deliver practical solutions.", conscious: "Line 5 (Heretic): Others project expectations onto you. You have the potential to offer universal solutions.", unconscious: "Line 1 (Investigator): You have a deep, unconscious need to investigate and build a solid knowledge base." },
  "5/2": { name: "Heretic / Hermit", theme: "Universal solutions through natural talent", description: "The 5/2 profile combines the ability to offer practical solutions with natural, innate talent. Others see you as a problem-solver, and your natural gifts support this role.", conscious: "Line 5 (Heretic): Others project their expectations onto you as a problem-solver.", unconscious: "Line 2 (Hermit): You have natural talents that support your ability to offer solutions." },
  "6/2": { name: "Role Model / Hermit", theme: "Wisdom through natural talent", description: "The 6/2 profile combines the journey toward role model wisdom with natural talent. You go through three life phases, developing your innate gifts into wisdom that inspires others.", conscious: "Line 6 (Role Model): You experience three life phases, eventually becoming a wise role model.", unconscious: "Line 2 (Hermit): You have natural talents that others can see, even when you can't." },
  "6/3": { name: "Role Model / Martyr", theme: "Wisdom through experience", description: "The 6/3 profile combines the journey toward wisdom with experiential learning. Your path involves deep experimentation, especially in the first phase of life, eventually leading to profound wisdom.", conscious: "Line 6 (Role Model): You experience three life phases on the path to becoming a role model.", unconscious: "Line 3 (Martyr): You learn through trial and error, gaining wisdom through direct experience." },
};
